### ISSUE TITLE
Content Highlight Bar Color Settings

### ISSUE THREAD

**Issue by CreativLogic** [facelessuser/BracketHighlighter#217]
Is there a way to change the content highlight bar color? I love this option turned on but it's the exact same color as my cursor. Thanks.

**Comment by facelessuser** [comment]
You can change your bracket color, and that will in turn change your highlight bar color, but that is all that is currently available.

**Comment by StreetStrider** [comment]
Hello.
Is it possible to customize highlight bar width? I want it to be 1px instead of 2px which is too thick especially in the time I'm having very bright color. I've tried to use alpha-transparent color, but this is resulted in poor bracket icons visibility (since they use the same color rule).
Accodring to documentation I can't customize it, but is this a limitation of ST API? Should I expect improvements in this part of styling? Thanks.

**Comment by facelessuser** [comment]
Limitation of ST API, sorry.
