### ISSUE TITLE
Tag highlight is not aligned

### ISSUE THREAD

**Issue by chumbothewhale** [facelessuser/BracketHighlighter#218]
Here's a screen showing the issue. Maybe it's just me?

![screenshot 2015-01-21 11 11 25](https://cloud.githubusercontent.com/assets/7739108/5843472/94efd652-a161-11e4-8917-4f158cadfea3.png)

Here's the code:

```html
<div class="content_wrapper">
    <div class="container">
        <div class="content_block row <?php echo esc_attr($gt3_theme_pagebuilder['settings']['layout-sidebars']) ?>">
            <div class="fl-container <?php echo(($gt3_theme_pagebuilder['settings']['layout-sidebars'] == " right-sidebar ") ? "hasRS " : " "); ?>">
                <div class="row">
                    <div class="posts-block <?php echo($gt3_theme_pagebuilder['settings']['layout-sidebars'] == " left-sidebar " ? "hasLS " : " "); ?>">
                        <?php if (!isset($gt3_theme_pagebuilder[ 'settings'][ 'show_title']) || $gt3_theme_pagebuilder[ 'settings'][ 'show_title'] !=="no" ) { ?>
                        <div class="page_title_block">
                            <h1 class="title"><?php the_title(); ?></h1>
                        </div>
                        <?php } ?>
                        <div class="contentarea">
                            <?php the_content(__( 'Read more!', 'theme_localization')); wp_link_pages(array( 'before'=> '
                            <div class="page-link">' . __('Pages', 'theme_localization') . ': ', 'after' => '</div>')); if (gt3_get_theme_option('page_comments') == "enabled") {?>
                            <hr class="comment_hr" />
                            <div class="row">
                                <div class="span12">
                                    <?php comments_template(); ?>
                                </div>
                            </div>
                            <?php }?>
                        </div>
                    </div>
                    <?php get_sidebar( 'left'); ?>
                </div>
            </div>
            <?php get_sidebar( 'right'); ?>
        </div>
    </div>
</div>
```

**Comment by facelessuser** [comment]
It's because PHP is messing up the HTML syntax.   See line 4 and line 6 (double quotes embedded in double quotes).   With things like PHP breaking the flow of HTML and the multiple variants of template languages out there, it becomes increasingly difficult to reliably find HTML tags.  If I keep relaxing the regex to find HTML that has PHP or Handlebars or whatever other scripting language or template out there, it will come to a point where I am getting false positives on HTML matches.

I know HTML is not meant to be parsed with regex as it is not a regular language, but that is the BracketHighlighter framework.  Maybe one day in the future things for HTML will be implemented a different way, but currently, it is done with regex, and  you can only stress those rules so much.

**Comment by facelessuser** [comment]
Reference of what I am currently working with: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_modules/tags.py#L10.
