### ISSUE TITLE
missing curly bracket highlighting

### ISSUE THREAD

**Issue by joewilliams** [facelessuser/BracketHighlighter#222]
I've tried this in ruby and it seems to work great but in a [TLA file](https://github.com/joewilliams/tla_tools/blob/master/examples/3pc.tla) it seems to miss the brackets.

![](https://dl.dropboxusercontent.com/s/narnrb4aibf4s2e/2015-02-06%20at%203.08%20PM.png)

My settings are:

`````
	"bh_toggle_enable": true,
	"high_visibility_enabled_by_default": true
`````

What do I need to do to get it to detect and underline those brackets?

**Comment by facelessuser** [comment]
It doesn't even look like you have a TLA syntax highlighter; I don't even know what TLA is.  By default, BH doesn't highlight in plain text files.

**Comment by joewilliams** [comment]
@facelessuser correct, afaik there isn't a syntax highlighter for TLA. Is it possible to toggle BH on for plain text files?

**Comment by facelessuser** [comment]
Yeah, you would have to modify the current bracket rules that you want to appear in plain text.  Plain text is usually excluded because brackets in strings or comments can't be filtered out.  Plain text isn't structured like code syntax, so you can get a lot of weird unmatched brackets in plain text without syntax context.

Anyways, you can remove `Plain text` from your desired rule's blacklist.  But keep in mind that not all rules will work or work well without syntax scoping context.

**Comment by facelessuser** [comment]
@joewilliams, I am assuming you have what you need now?  Or do you have any questions?

**Comment by joewilliams** [comment]
Thanks!
