### ISSUE TITLE
Possible to add dustjs templating support?

### ISSUE THREAD

**Issue by thisisbrianhan** [facelessuser/BracketHighlighter#234]
BracketHighlighter doesn't work when I set my syntax highlighting to `Dust`. 
I'm using the [dustbuster package](https://github.com/zanuka/dust-buster ) with sublime text to set my syntax.
Getting these two packages to be compatible would be great.

**Comment by facelessuser** [comment]
I believe it is possible (your link took me nowhere, so I am not sure what package you are using).

Just an FYI, I require the community to add support for desired languages as it allows me to focus on maintaining and adding features to the core, and you will understand the nuances of `dust` better than I.  With that said, I am more than happy to help guide you on adding your desired language, but I would first take a look at examples in the settings file, and I would also take a look at the documentation.

**Comment by facelessuser** [comment]
I am going to close this.  Hopefully someone will pull request this feature.  If you give it a shot and get stuck, I am open to guiding people through their issues, I just don't plan on spending time on implementing dust support myself since I don't know anything about dust (nor am I looking to learn :wink:).
