### ISSUE TITLE
Sometimes bracket highlighter stops working

### ISSUE THREAD

**Issue by xdmiodz** [facelessuser/BracketHighlighter#243]
Hi,

Thanks for the great plugin.

The plugin is a great relief for me to handle the template brackets in the C++ metaprogramming.
However sometimes the plugin just stops working and I don't know why. Under "stops working" I mean that the plugin doesn't highlight paired brackets, doesn't show the brackets on the right side of current pane, etc and there is no logs in the Sublime's log window. I know only one solution to this  - to restart sublime and it's not very convenient.

I don't have any logs to show you, but I can collect them If you share a clue how to do that.

**Comment by facelessuser** [comment]
I'm not really sure what you mean.  Some screencaps might help.  Now keep in mind that C/C++ programming allows for things like #if switches and such that can add quite  a bit of complication to files. They can allow for inserting of brackets that have no pairs that can throw off the matching.

For instance:

```c++
#if (CONDITION)
if (m_some_flag)
{
#else
if (m_some_flag && m_some_additional_flag)
{
#endif
// Some Code
}
```

Which opening bracket gets matched with the end bracket?  You can see the github Syntax Highlighter isn't even highlighting the `#endif` correctly because these types of situations add a much higher level of complexity.  Obviously this situation could be remedied above my moving the opening bracket after the `#endif` and just have a common one, but this is simply an illustration to show what I mean.  I won't go into the algorithm behind BracketHighlighter (BH), but it is simply not well suited for this type of situation as the unmatched bracket will throw off it's ability to pair other brackets. In general, I found that BH handles C/C++ code find in other scenarios.  I would have to do a lot of work to get BH to handle such complex scenarios, which  I currently have no interest in dealing with at this time (who knows maybe in the future).  I am a C/C++ programmer, and I do run into these kinds of issues in our code base, but in general, I just overlook these situations and currently accept this as a a weakness in the BH.

I don't even know if this is the kind of issue you are experiencing as I would need an example.

**Comment by xdmiodz** [comment]
I experienced the issue in much simpler situations. Here the screenshot of what I mean

![screen shot 2015-04-14 at 18 11 54](https://cloud.githubusercontent.com/assets/563026/7140027/f13a3fd6-e2d1-11e4-8bb8-326ac2a21b25.png)

On this screenshot BH works well - there are the underscores under paired brackets, the bracket mark on the right near the line numbers, etc. But under some conditions BH stops working on the same file. Unfortunately (or luckily) BH didn't encounter this conditions the time I took the screenshot, but I provide it as soon as I notice the issue again.

**Comment by facelessuser** [comment]
FYI, make sure you check the console for errors and such.  I would basically need either need a way to replicate the problem, or enough info like console errors to identify this as a BH problem.

Keep in mind that there may be the possibility that another plugin outside of BH may be interfering.

**Comment by xdmiodz** [comment]
After your note about interfering of plugins I think I found what the issue is. 
I have a git plugin to see diff in sublime. It opens another tab in sublime and shows everything I changed since the last commit.

So BH crashes while trying to parse the pane. Logs are the following:

```
Traceback (most recent call last):
  File "bh_core in /Users/dmitry/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 858, in payload
  File "bh_core in /Users/dmitry/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 380, in match
  File "bh_core in /Users/dmitry/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 446, in find_matches
  File "bh_core in /Users/dmitry/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 567, in match_brackets
  File "bh_search in /Users/dmitry/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 110, in new_bracket_search
  File "bh_search in /Users/dmitry/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 232, in __init__
  File "bh_search in /Users/dmitry/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 373, in findall
  File "bh_search in /Users/dmitry/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 273, in is_illegal_scope
IndexError: list index out of range
```
The result is on screenshot below - no underscores, no marks.

![screen shot 2015-04-14 at 18 45 09](https://cloud.githubusercontent.com/assets/563026/7140848/6a7a3b4a-e2d6-11e4-961d-e5a072afce62.png)

**Comment by facelessuser** [comment]
Cool, this gives me something to look at.  I will take a look.  What diff plugin do you use so that I can reproduce this?  I may be able to patch without it, but if I am able to install the plugin to reproduce, it will be much easier for me to understand why it is failing.

**Comment by xdmiodz** [comment]
Here it is

https://github.com/kemayo/sublime-text-git

The command that I use to see diff is "Git: Diff All Files"

**Comment by facelessuser** [comment]
Thanks, I will let you know when I have time to isolate the issue.

**Comment by facelessuser** [comment]
Okay, I cannot reproduce your problem.  But after looking at your screencaps and analyzing the section of code that your error is showing, I suspect I know what the issue is.

I believe you have added your own custom rules or modified existing rules?  If so, please post them.  I believe what you have done is broken some rules.  Each `open` and `close` entry must have 1 and only 1 capturing regex group.  If you don't have 1 group you mess up BH's ability to index the brackets.  This is covered in the documentation: https://github.com/facelessuser/BracketHighlighter#configuring-brackets-rules.

Please respond with the requested info so that I can confirm.

**Comment by facelessuser** [comment]
Also, oddly, your two screencaps seem to have slightly different syntax highlighting.  It seems some weird stuff is going on with your setup...

**Comment by facelessuser** [comment]
BH will now cleanly handle bad regex groups without crashing: https://github.com/facelessuser/BracketHighlighter/commit/d1f9128051e752e82cace9ac241fec909e584688.  When an invalid regex group amount is used, BH will now silently log the error in the console but continue cleanly.

**Comment by xdmiodz** [comment]
You are right, looks like it's my fault. I had custom angle brackets in bh_core, like this
```
  {
    "brackets":
    [
  // Angle
        {
            "name": "angle",
            "open": "(<)(?!\\?)",
            "close": "(?<!\\?)(>)",
            "style": "angle",
            "scope_exclude": ["string", "comment", "keyword.operator", "source.ruby.rails.embedded.html", "source.ruby.embedded.html"],
            "language_filter": "whitelist",
            "language_list": ["HTML", "HTML 5", "XML", "PHP", "HTML (Rails)", "HTML (Jinja Templates)", "HTML (Twig)", "HTML+CFML", "ColdFusion", "ColdFusionCFC", "laravel-blade", "C++"],
            "plugin_library": "bh_modules.tags",
            "enabled": true
        }
    ]
}
```

I've copied it from the default settings and and added C++ to language_list and this was crashing BH.

So I checked the manuals once again and replaced my custom configuration with the following:

```
{
    "user_brackets":
    [
  // Angle
        {
            "name": "angle",
            "language_list": ["HTML", "HTML 5", "XML", "PHP", "HTML (Rails)", "HTML (Jinja Templates)", "HTML (Twig)", "HTML+CFML", "ColdFusion", "ColdFusionCFC", "laravel-blade", "C++"]
        }
    ]
}
``` 

and now BH works like a charm. 

Thanks for support and sorry for bothering you!

**Comment by facelessuser** [comment]
It looks like your original method shouldn't have caused an indexing issue.  I will dig a little deeper and see if there is something else I am not accounting for.

**Comment by facelessuser** [comment]
Okay, technically your original pattern shouldn't have broken anything, though the new way you are doing things is much better and is the advised way.  After digging deeper, I found the actual issue and fixed it here: https://github.com/facelessuser/BracketHighlighter/commit/863abc4e60ea9b90d9569233806c6886f93c5510.

This fix should be in the next release.
