### ISSUE TITLE
Support JSX 

### ISSUE THREAD

**Issue by titoBouzout** [facelessuser/BracketHighlighter#252]
Hi there!

I just noticed /BracketHighlighter does not work with HTML in jsx files ! awww, it would be possible to add support for it? :)

Just take some sample from the home page https://facebook.github.io/react/index.html

**Comment by facelessuser** [comment]
It should be possible, but my current policy is that languages are supported by the community, unless it is a language I use.  I just don't have time to learn the nuances of new languages. So this is going to need a pull request.

**Comment by titoBouzout** [comment]
ok thanks

**Comment by PombaM** [comment]
:cry: :sob: :disappointed:

**Comment by sahilrajput03** [comment]
So whats the status for jsx now??

**Comment by facelessuser** [comment]
It's the same as it has always been. JSX has HTML snippets embedded in JavaScript. This creates complicated cases for BH. The context between two snippets could be entirely different, and since BH searches the buffer for matching tags, it can try to match unrelated tags in snippets. Not only that, since it allows basically templating variables in its syntax, it's not true HTML, and that syntax can also mess things up.
