### ISSUE TITLE
Several brackets highlight at the same time

### ISSUE THREAD

**Issue by norlin** [facelessuser/BracketHighlighter#253]
Hi, first – thanks for nice plugin!

But sometimes it make not so much sense – in case when I have a cursor inside string, or inside single-line brackets.

Is it possible to highlight (and draw icons on the left) for several parent brackets? (Say, for 3-5 levels, or by any other limit).

**Comment by facelessuser** [comment]
> But sometimes it make not so much sense – in case when I have a cursor inside string, or inside single-line brackets.

I used to at one time have an option to ignore matches on a single line, but on the rewrite, that didn't actually make it back in.  Maybe in the future it can make it back in.

I personally find single line inside strings useful when dealing with regex in strings; that is the main reason why I added the ability to do sub brackets inside strings.  Highlighting string quotes in general aren't really that useful, but everything is generalized in BH.  By targeting quotes, I can then utilize bh_plugins to select the string content, swap double to single quotes, jump to the end of the string, stuff like that.

> Is it possible to highlight (and draw icons on the left) for several parent brackets? (Say, for 3-5 levels, or by any other limit).

No, I've just never had adequate motivation to do something like that.  It would be a bit of work for something I don't think I'd ever use.  There is a lot I'd have to change to allow something like that.   BH is geared to target your current bracket scope.  Since everything is coded around that idea, it would be a pretty big thing to change
