### ISSUE TITLE
color setting doesn't work  (ST3083  BH2.8.1  win8.1) 

### ISSUE THREAD

**Issue by veniceXu** [facelessuser/BracketHighlighter#261]
![unnamed qq screenshot20150803172644](https://cloud.githubusercontent.com/assets/13161693/9052535/4bd7fa3e-3a9b-11e5-90af-e3e51132b165.png)
hello facelessuser ,I had config this package as you said in the doc,but there is some errors ,"unmatched" worked(red,"？"in the picture line:22,23),but others are all "default"'s style (orange,highlight)
worse still,when I uncomment "color" or "style" as required,it reports error all the time.enter image description here
i had even used the same theme as you did,and also config user-tmTheme file,but the error reports still exist
![unnamed qq screenshot20150803173017](https://cloud.githubusercontent.com/assets/13161693/9052554/7cda1b76-3a9b-11e5-89b9-76fb50f8dce7.png)
I had totally two things done as you said in docs,the one is to add <dict> in .tmTheme file ,the other is to uncomment user/bh_core.sublime.settings. the time when I uncomment, it reports error, then save user/bh_core.sublime.settings fails.

**Comment by facelessuser** [comment]
I am using the very latest ST3 and BH with custom colors.  Colors work great.  I can only assume this is a user error.  A matter of fact, in the picture you posted, a `:` is highlighted red because you forgot a comma after `curly_bracket`; so that is at least one of your issues.

Though I may generally instruct people to uncomment certain lines, I do expect that they will ensure that they do not break JSON format in the settings file.  I give general instructions, but I may not give **every** little detail.

The problem is because the you either haven't configured the settings file right, or haven't configured the theme file right.  Please try to make sure you have the proper syntax in both your theme file and settings.  If you are still struggling, I will require you to post your settings file and theme file here as the problem is is in one or both of those files.

**Comment by facelessuser** [comment]
I should say **color scheme** instead of **theme** file (in case there is some confusion here).

**Comment by veniceXu** [comment]
It works!! thank you very much!

**Comment by facelessuser** [comment]
No problem.  Glad you got it working.
