### ISSUE TITLE
HTML Tag Highlighting Problem

### ISSUE THREAD

**Issue by lakshyashah1988** [facelessuser/BracketHighlighter#262]
BracketHighlighter is not highlighting when there is php inside the HTML tag.

![screenshot_1](https://cloud.githubusercontent.com/assets/3746166/9102272/ef46b566-3c0d-11e5-9c0a-4aef67e6b690.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/3746166/9102273/ef48b0aa-3c0d-11e5-8812-36483f219b5f.png)

**Comment by facelessuser** [comment]
Since BH uses regex to find the tags, breaking the the HTML syntax with PHP tags breaks the bracket matching.  As PHP can be placed literally anywhere in HTML, it is impossible to come up with a regex that can account for the many diverse ways someone can break HTML syntax with PHP.  This extends not only to PHP, but to template languages with HTML as well.

The way the HTML code is parsed with the syntax highlighter lexer doesn't lend itself well to using scope bracket logic either.   I've tried to use the tag scope before, but touching tag scopes bleed together.

This is simply a limitation of BH at this current time.  The best way to handle this would be to tie bracket matching together with the syntax lexer, but that is something that BH can't easily do.

I currently leave language support up to the community.  If you can come up with a way to reliably handle this, I would be willing to merge it.  If you need additional support the core code to pull it off, I am open to a proposal.  If said proposal was accepted, I would have no problem implemented that code in the core.

We mainly have regex and syntax scoping to work with, if you can come up with a way to handle this in a general way that could work in the existing framework, then I am willing to move forward on this.  Any requests for code in the core must be general.  I will not add syntax specific code to the core, that is meant for bh_plugins.

**Comment by facelessuser** [comment]
I will close this as at this time there as I have no plans to move further on this.
