### ISSUE TITLE
Size of BH elements to the left of line numbers

### ISSUE THREAD

**Issue by sadokx** [facelessuser/BracketHighlighter#269]
Hi! Thank you for making this package!

As you can see from the screenshot below, the brackets to the left of the line numbers are really small. I searched a customizable setting in BH but found none related to sizing these elements. Is there any way to make them bigger? They are really hard to read. 

Thank you! Keep up the excellent work.

![image](https://cloud.githubusercontent.com/assets/12555077/9706785/1babeb78-54b7-11e5-916a-bb216b13a85e.png)

**Comment by facelessuser** [comment]
I'm going to go out on a limb here and guess you have a high resolution monitor?  Maybe 4K?

When text is real small, BH uses smaller icons.  When text is bigger BH uses bigger icons.  The size of icons used to be 16x16 px, but the actual image inside is what varies in size as it was found that the image would just stretch to fit the UI element.   With OSX retina displays, it was found that 32x32 px was sufficient to get a good icons in both retina and non-retina, so that is what is now used (though I have never physically confirmed it myself as I do not have a retina display).

At home I use OSX (no retina), but at work I use Windows with 4K monitors.  My brackets look small, so I am guessing your setup is similar?  On my 4K monitor, line height never drops below 16px, so BH never actually uses the smaller icons.  So it is always using the largest, which is still small.

On a non high resolution monitor, I have found the current setup works well.

But here's the thing, Sublime's icons are no larger than mine on my 4K monitor.  So I am doing things as good as Sublime is currently.  Try bookmarking a line and compare the icon sizes.

**Comment by sadokx** [comment]
Thank you for your reply.

It seems your Jedi senses are finely tuned: I am using a high res display. Here's the screenshot of the bookmarked line:
![image](https://cloud.githubusercontent.com/assets/12555077/9746286/b894d784-563c-11e5-974f-e52af1e12a1e.png)

So, same size as regular Sublime Text icons apparently. Do you know of any way to overcome this?

This is on Windows. I am getting a Macbook Pro Retina next week. Will it display properly?

Thanks!

**Comment by facelessuser** [comment]
> It seems your Jedi senses are finely tuned

The force is strong in my family

> So, same size as regular Sublime Text icons apparently. Do you know of any way to overcome this?

If I created new icons and used all the space available in the image, it would be marginally bigger.  Probably not really worth the effort to be honest.  I am currently taking the stance of as good as Sublime is good enough for me :smile:...I really just don't feel like redoing all the icons again for *maybe* slightly bigger icons.  When Sublime itself has a way to show bigger icons on a 4K, then I would probably force myself to get off my lazy butt.

> I am getting a Macbook Pro Retina next week. Will it display properly?

Theoretically, retina support was added by via pull request by someone who had a retina display...my wife has a retina display...maybe I should install this on her computer...I'll let you know what I find when I get a chance.  Retina just uses 2px for every 1px.  Since we provide a 32px image for a 16px image, it *should* look fine.

**Comment by sadokx** [comment]
Awesome. Thank you very much my man! Keep up the good work, yours is one of the most useful packages I've seen for ST. May your future (or current) children be blessed with a high midichlorian count, as yourself.

**Comment by facelessuser** [comment]
Checked out my wife's retina display.  Looks on par with non retina, so better than 4K.

**Comment by rodrigobutta** [comment]
Hi!! 
Nice conversation there, i've read it all. Now, a year leater, i'm still having this problem in a deamt 4k screen. Do you have any workarround there for me?? Thanksss from Argentina!!!!

**Comment by facelessuser** [comment]
If default Sublime icons still don't scale to 4k, then BracketHighlighter won't be able to scale either.  Until Sublime addresses this, the is no I can do.

**Comment by rodrigobutta** [comment]
I understand. Thank you!
