### ISSUE TITLE
Error trying to parse settings to bh_core.sublime-settings:1:2

### ISSUE THREAD

**Issue by visualsbysina** [facelessuser/BracketHighlighter#270]
Every time I open up Sublime Text 2, I get this error message:
Error trying to parse settings: Expected value in ~/Library/Application Support/Sublime Text 2/Packages/User/bh_core.sublime-settings:1:2

Not sure what is going on, as the bh_core.sublime-settings file is in fact present in the appropriate folder. I've tried removing and reinstalling brackethighlighter via package control multiple times, but this has not helped. Does anyone know what could be causing this?

**Comment by facelessuser** [comment]
You have formatted it incorrectly.  It should be in JSON format, but it allows Javascript style comments.  So if you are breaking the JSON format (trailing commas where there should be none etc.), then it will break in ST2.  Recent ST3 builds are more forgiving.  Since I don't see your bh_core.sublime-settings posted here, all I can say is double check your settings and format it correctly.

**Comment by visualsbysina** [comment]
Cool, well I ended up upgrading to ST3, but I actually had deleted all the original ST2 files, reinstalled, deleted again, reinstalled, same error. So my files must have been stock, but it kept giving me the error. Not sure why. Either way I'm happy with ST3, thanks for the help!

**Comment by facelessuser** [comment]
I am afraid I have no idea why ST2 was giving you issues, but I would suspect if there was a malformed stock settings file, then I would be having more than 1 person having trouble by now since I haven't made an ST2 release in over a year.

Anyways, I am glad ST3 is working for you.
