### ISSUE TITLE
Vintageous (block cursor) compatibility highlight mode. 

### ISSUE THREAD

**Issue by jordwalke** [facelessuser/BracketHighlighter#275]
Vintageous has two modes, and it is possible to query which mode you are in. One is standard "insert" mode and BH works fine in that mode. The other mode is equivalent to a one character wide selection range.

When the cursor is in insert mode, BH works fine and the `{}` are matched.

      [{   }|]

But when the Vintageous plugin is in `normal` Vim mode, there is effectively a block cursor that is *technically* exactly where the cursor was in the previous sample, but it has the conceptual meaning of being one character forward. I've placed `<>` where this conceptual cursor is located, though it is technically exactly where it was in the previous example (note that it conceptually spans a selection of size one - and the "block cursor" is painted *on top of* the right bracket `]`).

      [{   }<]>

Currently, the `{}` are highlighted, but a Vim user would expect the `[]` to be highlighted. Vintageous is a very popular plugin so it would be nice to get this to work out of the box.

You know if Vintageous is in this mode because the context is set to `vi_mode_normal_or_any_visual` - checking that would tell you if you need to compensate one character forward in the matching logic.

**Comment by facelessuser** [comment]
`<]>` and this `|]` are effectively the same thing, the only difference is your interpretation of it.  A block cursor and non block cursor are still positioned the same even though they are represented differently.

Your issue is that you don't want "outside adjacent" bracket matching when in a different vim mode.  BH defaults to the left if between two brackets for a consistent and predictable matching.  If you turn off outside adjacent matching in the settings file, you will only match brackets that the cursor is between, which in this case would be `[]`.

**Comment by jordwalke** [comment]
Right, and with Vintageous, you'd want to be able to switch between those two modes depending on which Vintageous mode you are in. This is indeed currently already working as expected - but what I'm requesting is a feature to integrate with Vintageous since it is such a popular plugin.

**Comment by facelessuser** [comment]
Why not add this to Vintageous?  It seems it would be better to add it there as you could add the code directly in at toggle state to change the BH setting.

I would have to intercept the toggle command and change the BH setting.  To be honest, this doesn't even have to be done in BH, you could have your own plugin that intercepts Vintageous toggle mode commands and changes BH's outside adjacent setting.  I personally am not interested in adding this code.

Personally, I think non-outside adjacent isn't what you really want.  What about this:

`<[>{}]`  Outside adjacent will select the `[` bracket; remember BH defaults to the left if it has to make a choice between a bracket on the left or right, but in this case the `[` bracket is clearly the one to choose.  Turning off outside adjacent in this case will select nothing as the selection is **not** inside and between `[]`, but it is on the outside to the left.  And what about this scenario `[{}]< >`, do you still want the square bracket highlighted?  I would think not based on your reasoning.

The truth is, what I think you really want is a special outside adjacent that will default to the right and possibly ignores to the left if it isn't in front of a bracket.  **Is this what you really want?**  If so, that would be a new and different bracket highlight convention.  Which means a bit of involved work.  Now, since I don't use Vintageous, my motivation for this is already a bit low.  As you are the only requester for this, I am still not sure I have sufficient reason to do this as at this time.  I could maybe add a block cursor mode that does as I described above, but I would need more people to be calling for this first as I would need to devote my free time to add such a feature.

I would probably still prefer Vintageous or a separate plugin to implement the bracket highlight mode toggle; I have purposely been avoiding adding code that is dependent on other plugins.

**Comment by facelessuser** [comment]
I'll at least look at how hard a block mode would be. If it isn't too hard, maybe I'll add it.  I did provide some abstraction for bracket selection already, so maybe it isn't as bad as i think.  At least then you could tap into it from vintageous or a separate plugin.

**Comment by facelessuser** [comment]
@jordwalke Okay, adding block mode wasn't too bad.  Here is a separate experimental branch: https://github.com/facelessuser/BracketHighlighter/tree/block.  Now to get this merged, I do expect you would give it a try and give feedback and note any bugs etc.

The following will highlight:

```
<[>some text]
[some< >text]
[some text<]>
```

The following will not highlight:

```
[some text]<>
<>[some text]
```

The following will yield the shown results:

| Scenario | Highlights |
|-------------|---------------|
|`<[>{}]`  | `[]` |
| `[<{>}]` | `{}` |
| `[{<}>]` | `{}` |
| `[{}<]>` | `[]` |

I have not figured out how this will play with `bh_plugins` like `bracketselect.py`, but that will be handled once I play with this more.

Again, I am not concerned with *how* this gets integrated with vintageous or other vim like plugins, but I am providing so it *could* be integrated in some fashion.  I don't want to add various implementations to support all vim like plugins.  Each one will need to do it themselves, or another third party plugin can integrate the desired vim plugin with BH.

**Comment by jordwalke** [comment]
Unfortunately, that did not seem to work (I tried all combinations of)

    "match_only_adjacent": true/false,
    "bracket_outside_adjacent": true/false,

Each combination of those settings failed in it's own to produce your table test cases.

**Comment by facelessuser** [comment]
Did you look at the new setting? Block_cursor_mode?  Obviously, I tested it before I let you know : wink:.

**Comment by facelessuser** [comment]
Well minimally tested it : smile:.

**Comment by jordwalke** [comment]
No I did not! Retesting.

**Comment by jordwalke** [comment]
Seems to work great!

**Comment by facelessuser** [comment]
Cool, finding bugs (if any) and making sure it works well with some of the bh_plugins, is all that is left.  After that, from a BH perspective, I will consider this done.

**Comment by jordwalke** [comment]
Okay, we'll let this bake (I'll test for a while) and then check back in with any additional bug reports?
Thanks for keeping your project tidy and well supported.

**Comment by facelessuser** [comment]
Added `block_cursor_selected_only` settings to provide a block mode equivalent of `match_only_adjacent`.  With this set along side `block_cursor_mode`, highlighting will only occur when the cursor is on top of (or selecting) either the opening or closing bracket.

https://github.com/facelessuser/BracketHighlighter/commit/7785bed7eb84600ffff52906509f78b173e398bc

Still haven't worked out how this is supposed to operate with bracketselect.py bh_plugin, but that is low priority for me.  Worst case scenario, bracketselect will ignore block mode, or simply disable expanding for block cursor mode.

**Comment by facelessuser** [comment]
Okay, I decided against using `block_cursor_selected_only`, we will just use `match_only_adjacent` for block mode and non-block mode.  `Bracketselect` should now work fine with block cursor mode; though it should be noted that bracket navigation with `bracketselect` will ignore block cursor mode as it hinders bracket navigation.

So I think I will play with this a little more and then probably add this noting it is an experimental feature.

**Comment by facelessuser** [comment]
Track progress over at #280.
