### ISSUE TITLE
Placing the cursor to the left of a bracket and pressing "Jump to left/right bracket" takes you the to matching left/right bracket of the enclosing bracket pair (or does nothing)

### ISSUE THREAD

**Issue by darkred** [facelessuser/BracketHighlighter#291]
The code for this is [here](https://www.reddit.com/r/Enhancement/comments/3tvn7h /tampergreasemonkey_script_for_those_who_have_been/), 
_(I thought to not quote it, because it's quite large)_. 

To reproduce (example) : _(using ST3 build 3095 -or 3083- with BracketHightter v2.10.1)_  
- please copy and paste the above code in a tab (Javascript)   

***

_Note: 
place the cursor(=click) to the right of the bracket in line 203 (the bracket is highlighted and a `?` appears in the gutter).  Now, pressing `Ctrl+Win+Alt+B`("Match brackets(ignore threshold") shows that it's left bracket is in line 18. 
Also, placing the cursor to the left of that bracket (the bracket is hightlighted as well, like before) and pressing `Match brackets(ignore threshold)`,  shows line 18 again, as expected._

***

- Now, place the cursor to the **right** of the bracket in line 203 again and press `Ctrl+Win+Alt+Up`:   
it doesn't go to the end of line 18, as expected - instead it does nothing.  
Now, place the cursor to the **left** of the bracket in line 203 and press `Ctrl+Win+Alt+Up`:   
now it works ok (takes you to line 18). 
- Also, placing the cursor to the **right** of the bracket in line 202 and press `Ctrl+Win+Alt+Up`,  
takes you to line 18 _(instead of line 192)_.  
Placing the cursor to the **left** works ok. 

This issue occurs for any other bracket in the script.

Thank you

PS. The above script didin't show any (bracket-related) errors  in jshint.

**Comment by facelessuser** [comment]
> place the cursor(=click) to the right of the bracket in line 203 (the bracket is highlighted and a ? appears in the gutter). Now, pressing Ctrl+Win+Alt+B("Match brackets(ignore threshold") shows that it's left bracket is in line 18. 
Also, placing the cursor to the left of that bracket and pressing Match brackets(ignore threshold), shows line 18 again, as expected.

1. There is no line 203 in the example code you pointed me at.  Maybe I am confused, but the there were only 172 lines in that snippet.

2. Anyways, as for getting the `?` and then not getting the `?` when ignoring the threshold should be clear.  BH uses a search threshold.  It will only search so far before giving up to on auto matches.  Since auto matches are performed quite frequently on selections, and edits, we don't want to do excessive searching for performance reasons.  If you want to increase your threshold in the settings file, feel free to find a value that works best for your performance and distance for you.

3. As your snippet didn't have line 203, I can't comment further on your other points.

**Comment by darkred** [comment]
Please copy-paste it from http://pastebin.com/XaGNxQ6d then

**Comment by facelessuser** [comment]
> Now, place the cursor to the right of the bracket in line 203 again and press Ctrl+Win+Alt+Up:
it doesn't go to the end of line 18, as expected - instead it does nothing.
Now, place the cursor to the left of the bracket in line 203 and press Ctrl+Win+Alt+Up:
now it works ok (takes you to line 18).
Also, placing the cursor to the right of the bracket in line 202 and press Ctrl+Win+Alt+Up,
takes you to line 18 (instead of line 192).
Placing the cursor to the left works ok.

This is actually expected.  Let me explain:

BH deals with one bracket pair during a command, it is not aware of parents, but it has the ability to to jump up through the parents if you keep pressing `Ctrl+Win+Alt+Up`....so why is that?  Well because when doing jump mode, if you are outside of a bracket, it turns off outside adjacent matching even if you have it enabled so that it will find the parents and not the adjacent.

If you don't like this behavior change this setting http://facelessuser.github.io/BracketHighlighter/customize/#ignore_outside_adjacent_in_plugin.  But then you won't be able to jump to the parent.  This is a current limitations in BHs algorithm.  I want it to be fast, so it concerns itself with the least number of matching brackets (1).  It doesn't care about the parents, because matching the parents takes more time.

**Comment by darkred** [comment]
Alright, then. Thank you for the detailed reply.
