### ISSUE TITLE
Swap quotes does not work for JSON files

### ISSUE THREAD

**Issue by ezk84** [facelessuser/BracketHighlighter#295]
I have the following in a JSON file:

```javascript
{
    "id": 'test',
    "first_name": 'Test',
    "last_name": 'Test',
    "address": {
        "point": {
            "lat": 1,
            "lng": 1
        }
    }
}
```

I move the caret to the id field's value and either select the "Swap Quotes" command from the palette or press the keyboard shortcut and nothing happens.

**Comment by facelessuser** [comment]
Yes, because BH's swap quotes feature is scope based because BH quote detection is scope based.  It works in languages that support both quote types.  JSON syntax highlighter only supports double quotes because the JSON syntax only supports double quotes.

Switch your syntax to JavaScript and you will see that swapping works fine as JavaScript scopes both single quote and double quote as strings.  It is just a limitation of BH.  The bh_plugins can only work with brackets that BH actually identifies, and BH currently only identifies quotes when scoped as string.

**Comment by ezk84** [comment]
Ahh! Okay, that's a shame I thought it would work in any place where quotes are found. Cheers!

**Comment by facelessuser** [comment]
Finding quotes well requires either context or for you to parse the file from the beginning.  I won't go into the details,  but since BH tries to do the least amount of searching,  it uses scope for context.
