### ISSUE TITLE
Error in showing highligher

### ISSUE THREAD

**Issue by jawahar5** [facelessuser/BracketHighlighter#300]
![error](https://cloud.githubusercontent.com/assets/10827895/12019036/5307dff4-ad91-11e5-9a71-fec10cae1d7c.PNG)
At times the braces are shown only as ?. works only with simple code. not working well in places like commit and rollback type codes are to be done.

**Comment by facelessuser** [comment]
This is a fairly common question that I have answered many times.  A search in the issues will bring up the answer:

https://github.com/facelessuser/BracketHighlighter/issues/181#issuecomment-49748985

I would advise you read the documentation or even read the info provided in the settings file.

In short there is a search threshold that is fairly conservative out of the box that can be adjusted; this is there by design for performance.  There is also an on demand match command in the palette for times when you really want to match without the threshold.
