### ISSUE TITLE
Wrong matching keyword for conditional after append operator in block (Ruby)

### ISSUE THREAD

**Issue by iBublik** [facelessuser/BracketHighlighter#301]
It looks like there's some mistake with finding opening keyword. When I use condition after append operator it shows that opening keyword for `end` is `do` in the block declaration. See example on the screen:
![image](https://cloud.githubusercontent.com/assets/11278497/12244611/64d26e80-b8c6-11e5-89c6-84d385daf9c0.png)
But the correct opening keyword is `if` like with simple assignment on the following screen:
![image](https://cloud.githubusercontent.com/assets/11278497/12244665/92937a44-b8c6-11e5-90cf-1e6457500bb0.png)

**Comment by facelessuser** [comment]
Yeah, I am sure it is because of the syntax used in the upper example.  I don't use Ruby and a number of "supported" syntaxes used in BracketHighlighter, so I don't know all the nuances of different languages.  I really don't have the time to dig into every language that people want supported.  For this reason, language rules are supported by the community as noted in the documentation http://facelessuser.github.io/BracketHighlighter/contributing/#overview.  Feel free  create a pull request to address the Ruby issue.  Keep in mind though, that I am generally available to answer general questions you may have if you are struggling with modifying the bracket rules.

**Comment by iBublik** [comment]
@facelessuser Ok, thanks for clearing it out. And thanks for the great plug-in too.
