### ISSUE TITLE
Add C Improved

### ISSUE THREAD

**Issue by xtotdam** [facelessuser/BracketHighlighter#311]
Hi! Great work!
Could you please add "C Improved" to default settings to section "C/C++ compile switches" to languages list?

**Comment by facelessuser** [comment]
Hey, glad your interested in BracketHighlighter.  Because I am so busy, I mainly only work on issues in the core framework of BracketHighlighter.  Syntax support is supported by the community via pull requests as stated in the documentation: http://facelessuser.github.io/BracketHighlighter/contributing/#overview.

I'd be happy to merge a pull requests.  If I am not mistaken, you should already have `{}`, `[]`, and `()` support in C Improved.  What support exactly are you hoping to be added in `C Improved`?

**Comment by xtotdam** [comment]
Yes, `{}`, `[]`, `()` already do work as expected and a little bit better =) But `#ifdef`, `#endif` etc are not yet highlighted. I will create a pull request, if I will be able, am really busy too.

**Comment by facelessuser** [comment]
As a very busy man as well, I understand.  If you run into issues, I don't mind providing guidance or advice when you get around to working on it.

**Comment by xtotdam** [comment]
Oh, I am very sorry for the lack of information about this issue in my first comment, honestly, should have written more.
