### ISSUE TITLE
Ignore (or consider secondary priority) of brackets in-text

### ISSUE THREAD

**Issue by stdedos** [facelessuser/BracketHighlighter#318]
Version: # BracketHighlighter 2.12.0 / Sublime 3 (build 3103)

Sometimes I write error messages with a sad emoticon
`"Sorry, this does not look good :("`

or use literates in LaTeX (recently supported)
`{(} { {\textbf{(}} }1`

But this messes with the highlighting.

PS: I know this could be a pita to work around - consider it a low-prio or ask me for more code to help you solve this.

**Comment by facelessuser** [comment]
> Sometimes I write error messages with a sad emoticon
> `"Sorry, this does not look good :("`

This is because BH is always going to have a difficult time with plain text as plain text isn't structured like code is.  For instance, plain text is usually confined to either comments and strings in code which allows BH to simply ignore those scopes. Not so with plain text documents.  You are free to modify/override the bracket rules with more complex regex to try and avoid such things in your LaTeX/Markdown/whatever files.  I would simply exclude your file's source scope from the default round bracket rule and maybe add a new bracket rule specifically for the language(s) of interest provided a regex that maybe has a lookback or something similar to exclude emoji like characters that come before or after `)` or `(`.

> or use literates in LaTeX (recently supported)
> `{(} { {\textbf{(}} }1`

This statement illustrates that you are more knowledgeable about LaTeX than I am.  For this reason, bracket rules are supported by the community: http://facelessuser.github.io/BracketHighlighter/contributing/#overview.  I simply don't have the time to learn the nuances of everyone's favorite languages.   I usually add modify rules of languages I use, but leave all other languages up to the community to support.

I provide the framework and documentation, and the community adds the rules they are interested in.  Keep in mind, I am willing to give ideas, advice, guidance to help about, but I leave it to the community to issue pull requests.  So if you run into problems trying to put together a pull request, or aren't exactly how to approach a certain bracket issue, feel free to ask questions.

**Comment by facelessuser** [comment]
As syntax specific changes are supported by the community via pull requests, this issue will be closed as I do not plan on personally spending time on it as I don't use LaTeX.

**Comment by stdedos** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Maybe label it and store it away as a to-do or something?

On 6/4/2016 6:25 μμ, Isaac Muse wrote:
> As syntax specific changes are supported by the community via pull 
> requests, this issue will be closed as I do not plan on personally 
> spending time on it as I don't use LaTeX.
> 
> — You are receiving this because you authored the thread. Reply to
> this email directly or view it on GitHub 
> <https://github.com/facelessuser/BracketHighlighter/issues/318#issueco
mment-206426127>
>
> 
- -- 
Yours faithfully,
Ntentos Stavros
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2
Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iQIcBAEBCAAGBQJXBSrWAAoJEAQJ50Mm6gMIbzsQAIF/JdzaGhaVMYGtzkVm+Mop
84muKoxZX9pvD4alpDM665GzLcNV9d9oDvTZJwdYkgAyMFvSWBXXMYfrxZozRIgm
EycJMrf5jvhQjEeRUiyC+lmFvf9LZLQfs9We+xF7YpYPHoO8nonyOTknATopzqqN
SVMMCCoS1b9LtSiqTlxH9Xq6FDctpMqe4G1W2qzoWaUEZ8FYTmQhvwWWWDvRurDa
+m/aw7wRB0ArLC0EInaIyUaJc4Oi3oS/j88D3VWUi8+m8U3wfxlJVlD0ChmVHquP
rzha45BkbaNbl8U70dSr0BMyVCPJgRLni7qpjMyQ1WPKYFIFbJxlgWg9nZ/QjruJ
DiMWv0p3jwEMaTEZyF5/Qhaf/1izDvzZG814Oy/OWgc0jisKY7+Z8rXBWn4kZ7XG
EpPpBo9stu0UaS3NbJLu9SdmAbZW4+WbsfAIAWZ+wAXPz/zDvLx+DYahBocWst8z
r3y91iNelIr1/HBvBZvMfy6ms4oyziB7eHRYOu+ZrXNLXfXL52fIIwunsTvoTKTp
oKP0ATjrUyVDp2qonp6lx3C3gU/XoK5WFgI2ggCvW9bm7FOYXXsUz2MDTIWmEyj0
QRIgH41+M0d+uBKPCF/dpfzCacyHJKG/GuX7x9RfZcDT4OXHbVGnWF5WZwuIYQIK
8e7TA4aqdxcTzW6Ru55z
=k3uq
-----END PGP SIGNATURE-----

---
Αυτό το e-mail ελέγχθηκε για ιούς από το πρόγραμμα Avast antivirus.
https://www.avast.com/antivirus

**Comment by facelessuser** [comment]
> Maybe label it and store it away as a to-do or something?

But that is the point, it isn't something I plan on doing.  It is tagged as `Pull Request Only`.  I could leave it **open** for someone later to come and see and fix, but I will be honest,  no one comes to the BH issues to look for issues to resolve except me as I am the maintainer (at least I am yet to see anyone).  I don't have a team, so I don't have anyone to assign tasks to outside myself.  So if it isn't an issue that I specifically plan to work on, it usually gets closed as it is just noise for me.

The only people who historically create pull requests for BH (or any of my Sublime related repos) are those who have a specific issue and have the motivation to solve it themselves.  So I usually inform the person who creates an issue that they are welcome to create a pull request (if it is something I decide to pass on), and if I don't  see any activity after a while, I assume they have no intention to personally address the issue (which is fine, I understand that people are busy, or maybe creating a fix is too difficult for them).  So I close the issue and await the next person to see if they will be more motivated.  I usually reference any past requests.

Github doesn't allow me to set up default filtering rules to hide stuff I don't care about, so leaving issues like this open just creates noise for me that I don't want.  If I am still considering an issue or just don't have the time right now, but plan to address it in the future, I leave it open.  This helps keep my backlog clean of issues that I am not going to touch.

**Comment by r-stein** [comment]
At least for the second part you can easily just disable round parens in LaTeX:

Add to the user bracket settings (`Preferences >>> Package Settings >>> Bracket Highlighter >>> Bracket Settings - User`) the language LaTeX to the blacklist for round brackets
``` js
{
    "user_brackets": [
        {
            "name": "round",
            "language_filter": "blacklist",
            "language_list": ["Plain text", "Hex", "LaTeX"],
        }
    ]
}
```

**Comment by facelessuser** [comment]
@r-stein Thanks for taking the time.  @stdedos I would take a look at r-stein's suggestion, it will definitely solve the round bracket in LaTeX issue for you.  You can probably leave out redefining the `language_filter`; you only need to define the `name` and the key you want to override, in this case, `language_filter` is still the same, so no need to include it (but it won't hurt anything).
