### ISSUE TITLE
Seems to ignore threshold setting

### ISSUE THREAD

**Issue by kgizdov** [facelessuser/BracketHighlighter#319]
Hi,

I used to be able to set the search threshold to 10000 in order to deal with the size of the code I have. Recently however, that has been problematic. In fact, it does not matter what the search threshold is set to, it defaults to the build-in limit and ignores user setting. This doesn't break functionality but is really annoying when I want to make sure a bracket is properly closed when the loop/if statement is out of the page. Could you help debug this?

**Comment by facelessuser** [comment]
> In fact, it does not matter what the search threshold is set to, it defaults to the build-in limit and ignores user setting. 

This is simply not what I see.  The threshold works for me.

> Could you help debug this?

- I don't know what your code looks like or how much content is between your brackets.
- I don't know if you've configured your settings right or named the settings file proper in your user folder to override the default.
- There are a lot of things I don't know about your setup right now.

Without more info, I can't possibly help.  There could be any number of reasons you aren't getting the results you expect: not configuring the settings correctly, misinterpretation of settings, something corrupted in your sublime setup, a bug in the code, etc. I will need very specific examples for me to even begin to assess the issue.  I will say this though, there are times brackets will be very far apart, and auto-matching them on selection would cause too much lag; this is why the threshold exists.  But there is a command palette command `BracketHighlighter: Match Brackets (ignore threshold)` which will ignore the threshold and match the brackets no matter how long it takes.  It is an on demand command so you can run it only when you need to.

I think it's a bad idea, but due to requests, I also have the setting ` "ignore_threshold": false`.  I will always discourage usage of this, but I added it to appease those who kept requesting such a setting.  If you enable this and have terrible performance in large files, that is on you.

I would play with the  `search_threshold` to find a good compromise of functionality  and performance.  This will differ from machine to machine.  If the setting isn't working for you, I would double check that you are overriding it in the proper file name.  Double check the setting name.  Double check the console to make sure you aren't getting an settings error (like if you got the JSON format wrong), etc.

For more help, you will have to give me very specific examples that I can reproduce the issue with.

**Comment by kgizdov** [comment]
It was working before and I haven't touched it until I started seeing the errors. Deleting and recreating the file, seems to have fixed it. Maybe something got corrupted as you said.

Didn't know about the command palette option. This toggle per case is much better than having a huge threshold all the time. I will start using that when needed instead. Thanks for the help.

**Comment by facelessuser** [comment]
> Didn't know about the command palette option. This toggle per case is much better than having a huge threshold all the time. I will start using that when needed instead. 

Yeah, that is the way I use it.  It just doesn't make since to push it super far.  I use about `10000` and that works smooth on my computers.  Anytime bracket content exceeds that, I just use the manual option when I **need** to find the other bracket.

Anyways, glad you got it working.
