### ISSUE TITLE
Macros Fail

### ISSUE THREAD

**Issue by rodrigobarrocal** [facelessuser/BracketHighlighter#320]
I can not use the commands in macros, error: Unknown macro command bh_modules.tagnameselect

**Comment by facelessuser** [comment]
Based on the error, it would appear you are setting up the macro incorrectly, but you didn't post the macro content so I cannot be sure.  If you would like me to comment on the macro, you will have to post it.

Second, the main BH command is a WindowCommand instead of a TextCommand, so I imagine it wouldn't work in macros as it is now.  I believe it is required for the commands that are used in macros to be TextCommands.  Maybe in the future this could be changed.

**Comment by facelessuser** [comment]
I will look into potentially changing this to use a TextCommand instead of a WindowCommand.  I cannot promise when I will get around to validating such a change, but I will look into and make a decision.

**Comment by facelessuser** [comment]
Recently I moved BH commands to TextCommands.  Unfortunately it didn't seem to make any difference.  I think Sublime is very limited in what gets tracked in macros.  Sadly, based on what I know at the present, I don't think I can fix this.  If I or someone else brings to my attention more info to help resolve this, I will reopen.
