### ISSUE TITLE
Valid unquoted html attribute value not handled well

### ISSUE THREAD

**Issue by medifle** [facelessuser/BracketHighlighter#330]
- Sublime@Build 3103
- OS X@10.11.4

Reproduce the issue:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <div class="" data-percent=64.4>
    <div class="">
      <div class=""></div>
    </div>
  </div>
</body>
</html>
```

In this case, the `data-percent` attribute has an unquoted but valid value(see [here](https://mathiasbynens.be/notes/unquoted-attribute-values), and [here](https://mothereff.in/unquoted-attributes#64.4)), however BH performs differently than in the case of using quoted attribute value.

Here is an img showing the problem when I use valid unquoted attribute value:

![image](https://cloud.githubusercontent.com/assets/13296643/14599260/ef2da900-0588-11e6-88dd-2d00b75cbfc1.png)

Another img when I use quoted attribute value:

![image](https://cloud.githubusercontent.com/assets/13296643/14599356/77a36590-0589-11e6-936c-c2b778f295d7.png)

**Comment by facelessuser** [comment]
Ughh.  The current detection works for HTML and XML as unquoted attributes are not valid in XML.  I personally never use unquoted attributes as the very thought makes me cringe, not because I don't understand them, but because a lot of other people don't understand them.  You are the first to report this problem as I imagine you are one of a very few who ever used them.

Anyways, I guess it isn't really important how I feel about them, but that they should be handled proper.  I usually leave language issues up to pull requests, but since I do use HTML, I will address this personally.

**Comment by facelessuser** [comment]
Just a note: this issue was introduced in #308.  I originally removed this code because the regex hanged.  This new fix does not seem to cause a hang.
