### ISSUE TITLE
Custom highlight color doesn't work.

### ISSUE THREAD

**Issue by gotofritz** [facelessuser/BracketHighlighter#331]
Hi. I tried to customise BH so that I don't have to use the default white. But it simply doesn't work.

bh_core.sublime-settings in my User folder:

    "bracket_styles": {
        "default": {
            "icon": "dot",
            "color": "brackethighlighter.fritz",
            "style": "outline"
        },

        "unmatched": {
            "icon": "question"
        },

       // etc, no colors defined except for "default"

My theme (Brogrammer)

      <dict>
            <key>name</key>
            <string>Bracket Default</string>
            <key>scope</key>
            <string>brackethighlighter.fritz</string>
            <key>settings</key>
            <dict>
                <key>background</key>
                <string>#606060</string>
                <key>foreground</key>
                <string>#CC99CC</string>
            </dict>
        </dict>

What am I doing wrong?

Why does it have to be so difficult, why not just let us change the "internal default" which is white (not a great choice, it doesn't work on light backgrounds and it's too bright on dark ones) without having to fiddle with theme files? Personally I don't need all the complexity, I am happy with just ONE color for all type of brackets, too many options drive me mad.

Thanks.

**Comment by r-stein** [comment]
Do you have Color Highligher installed? That package creates a copy if your colorscheme, such that changes does not directly have an effect. You can open the console `` ctrl+` `` and write `view.settings().erase("color_scheme")` to update the colorscheme.

The highlighting color is limited by the sublime api, which requires a scope to define the highlighting color and you can not simply pass the color itself. It is white because your colorscheme does not define the scope `brackethighlighter.default` and hence that is highlighted by the default color of your colorscheme, which is usually white.

**Comment by facelessuser** [comment]
> But it simply doesn't work.

It does.

> What am I doing wrong?

Could be a number of things.

- I see what you put in your color scheme, but I have no way to verify it is placed in appropriately.
- Do you use SublimeLinter?  If you do, SublimeLinter has a habit of copying themes and changing its name to `yourtheme(SL).tmTheme`; I forget where in your User folder it places them, but you get the idea.  So if you do use SublimeLinter, and you change your original theme, Sublime is probably pointed at your SL version instead, so you have to rest your colorshcme to the original, and then SublimeLinter will recreate your SL version...I know...
- Something else I am unaware of.

> Why does it have to be so difficult

I would prefer to just give BH a color opposed to scopes, but I don't get to make that decision.  This is a limitation of the Sublime API.  Some people want the ability to color different brackets differently.  More options requires more complexity.

> why not just let us change the "internal default"

You can.  You don't have to create your own scopes for individual brackets, you can just change the default one.  You can leave your color scheme untouched if you want as well.  Instead of creating your own scopes, you can use one of the existing ones in your color scheme.

I have to work in the environment that Sublime allows.

**Comment by gotofritz** [comment]
Hi thanks for your prompt answer and your patience :-)

It was indeed Color Highlighter causing the issue, Sublime simply ignored any color scheme I tried to install EVEN after uninstalling Color Highlighter (it kept living in the Local/Session.sublime_session file). It seems that under the bonnet Sublime is rather messy. 
[resolves to learn VIM and dump sublime]

**Comment by facelessuser** [comment]
> It was indeed Color Highlighter causing the issue, Sublime simply ignored any color scheme I tried to install EVEN after uninstalling Color Highlighter (it kept living in the Local/Session.sublime_session file). 

I'm honestly not a huge fan of that plugin.  It is extremely invasive and at times fragile.

> It seems that under the bonnet Sublime is rather messy.

Meh, it isn't perfect, but I am yet to find an editor that is.  I personally think it is a small thing.  Once I set up my color scheme or settings file, I don't have to look at it again.

> [resolves to learn VIM and dump sublime]

 Sublime isn't for everyone, nor is any editor.  To each their own.  VIM just never worked the way I work, but I know some people that swear by it and are very fast with it.
