### ISSUE TITLE
Highlight content like racket

### ISSUE THREAD

**Issue by thenikso** [facelessuser/BracketHighlighter#333]
Hello!

I wonder if it could be possible to highlight selected brackets' content background like in racket:

![Racket brackets highlight](https://docs.racket-lang.org/drracket/example.png)

Thanks!

**Comment by facelessuser** [comment]
Due to the way the Sublime API handles highlight regions, it isn't really practical as an "always on" feature (as least I don't think so, but some people like it).  But there is a high visibility mode available that is available that basically does this.

If you try to highlight the background with the Sublime API the solid style, the color of the text is all white or black (depending on what Sublime picks for to standout with the background) and you loose syntax highlighting in that region.  By default I think I set the feature up with an outline which allows the syntax highlighting to still work.  It works, but I personally only turn it on when I really need to increase the visibility (such as files with ridiculous nesting of brackets).

There is a command in the command palette to toggle the high visibility mode.  If you need to turn it on by default or tweak the style etc., you can see the high visibility settings here: http://facelessuser.github.io/BracketHighlighter/customize/#high_visibility_enabled_by_default.

**Comment by thenikso** [comment]
thanks this solves my question. I'm using the `content_highlight_bar` instead.

**Comment by facelessuser** [comment]
> thanks this solves my question. I'm using the content_highlight_bar instead.

Understood.  I guess we have a couple of features in there that do similar things.  Everyone likes something different :).
