### ISSUE TITLE
ES6 Arrow Functions break Bracket Highlighter

### ISSUE THREAD

**Issue by wesbos** [facelessuser/BracketHighlighter#341]
Hey! Love this plugin - I make all my students install it and it saves us so much time. 

Now that I'm teaching arrow functions in JavaSCript, it seems that code like this will break the function block, or the curly brackets that define the function.

![](http://wes.io/gLiS/content)

You'll see that the sublime match brackets is working, but the sidebar from this plugin is confused. 

```js
function convertCurrency(rate, ...amounts) {
  console.log(rate, amounts);
  return amounts.map(amount => amount * rate);
}
```

It does the same on open

![](http://wes.io/gM51/content) 

Any way we can fix this?

**Comment by facelessuser** [comment]
You will most likely have to modify the angle bracket rules.  Usually we don't disable angle bracket support in JS because JS is mixed with HTML (and we want to find angled brackets in HTML).  Looking at your image, there is good news as it appears that your syntax highlighter scopes ES6 `=>` notation.  We can use that to exclude the scope of `=>` in the angle bracket rule: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.sublime-settings#L316.

Please issue a pull request for others when you are able to target the correct scope.  If you are still having issues, just let me know and I will see if I can offer some other suggestions.

**Comment by facelessuser** [comment]
I went a head and plugged your example into some HTML and (at least with the JS syntax highlighter I am using) this scope exclusion seemed to work `storage.type.function.arrow.js`.  I didn't test beyond a quick check, but maybe that is what you need.  This may vary form highlighter to highlighter which is why I usually just have the affected party issue a pull when they encounter such issues.

![screenshot - 6_2_2016 2_10_01 pm](https://cloud.githubusercontent.com/assets/1055125/15759427/cc77c0ec-28cb-11e6-9faa-3a1a120f105a.png)

**Comment by wesbos** [comment]
Cool - do you have that in a branch so I can try it? I'll test with the three major JS highlighters

**Comment by facelessuser** [comment]
I don't, I just dropped this in my `User/bh_core.sublime-settings`:

```js
    "user_scope_brackets": [],
    "user_brackets": [
        {
            "name": "angle",
            "scope_exclude": [
                "string",
                "comment",
                "keyword.operator",
                "source.ruby.rails.embedded.html",
                "source.ruby.embedded.html",
                "storage.type.function.arrow.js"
            ]
        }
    ],
```

`user_scope_brackets` and `user_brackets` are used to either insert/append new rules or modify existing rules (but just the fields of existing rules you need to :wink:).  The way it works is if you use a `name` that already exists, you can just specify the keys of that rule that you want to override.  The rest of the keys will use their values found in the default settings file.

**Comment by facelessuser** [comment]
It looks like the scope I mentioned fixes this in the default Javascript and JavascriptNext which supports ES6 (both of which I happened to have installed).  I will commit the changes and consider this closed as this will be fixed in the default JavaScript that is provided with Sublime (and additionally JavaScriptNext).  If I have missed your specific JavaScript highlighter, just issue a pull request to fix that.

**Comment by wesbos** [comment]
Thanks @facelessuser :)

**Comment by wesbos** [comment]
Do you need to cut a release for this to be updated?

**Comment by facelessuser** [comment]
Yes, I need a release, but I was planning on doing some php rule fixes before that happens; just haven't had that moment yet to sit down and do it.

**Comment by facelessuser** [comment]
I thought I'd be able to work out what I needed to by yesterday, but since I didn't, I will do a release today.

**Comment by facelessuser** [comment]
Release was made.
