### ISSUE TITLE
It couldn't highlight this php tag in one line

### ISSUE THREAD

**Issue by nicolasxu** [facelessuser/BracketHighlighter#342]
` <?php if ($title): ?><h1 class="title" id="page-title"><?php print $title; ?></h1><?php endif; ?>
`

It can highlight it correctly after I format this line to multi lines, but can't highlight it if it is in single line.

**Comment by facelessuser** [comment]
You need to be a bit more specific with "but can't highlight if it is in single line".

**Comment by nicolasxu** [comment]
<?php if ($title): ?><h1 class="title" id="page-title"><?php print $title; ?></h1><?php endif; ?>
There is question mark "?" at the beginning of the line, and there is no highlight. 

If I change the one line code to the following multi line code. It highlights well. 
<?php if ($page['highlighted']): ?>
  <div id="highlighted">
    <?php print render($page['highlighted']); ?>
  </div>
<?php endif; ?>

**Comment by facelessuser** [comment]
This is a conflict most likely between using `<?php ?>` detection and phpkeywords (`if endif` etc.) detection.

BH can't deal with situations like this `[(] [)]`.  It will think that the round bracket is broken, and then won't be able to resolve the square brackets either. This is a problem because you can do some wacky things with PHP and some other languages.  For instance in C, you can do stuff like this:

```c
#if SWITCH
if (condition) {
#else
if (condition && other_condition) {
#endif
/*some code*/
}
```

Which opening curly bracket do I match the closing bracket to?  The correct answer is both, but BH doesn't have that intelligence.

To be honest, in HTML I do **not** think you should enable PHPkeywords **and** PHP angle brackets; you should really pick one or the other.  Depending on how crazy you get with your PHP conditionals, I imagine there can sometimes be some issues with HTML tags and PHP as well, especially if you create a scenario like I showed with C above.  PHP is like a preprocessor step on the HTML, that kind of complexity just is a bit much for BH.

Second the regex for PHP keywords isn't the best.  The rule was sloppy and doesn't allow for conditional ends on the same line as conditional starts (it also doesn't handle comments after conditionals).

For the first issue, you can disable either PHP keywords or PHP angles.  For the second issue, we need a better regex.  I don't really use PHP much, but if you can test the following and let me know how it works for you, I can add the new regex in:

Add this in your `User/bh_core.sublime-settings` file to override the parts of the rules we need to:

```js
    "user_brackets": [
        // PHP Angle
        {
            "name": "php_angle",
            "enabled": false
        },
        // PHP Keywords
        {
            "name": "php_keywords",
            "open": "(?:^\\s*|<\\?(?:php)?\\s*)?\\b(if|foreach|for|while|switch)\\b(?=.*:\\s*(?://.*?|/\\*.*?\\*/\\s*?)?(?:\\?>|$))",
            "close": "(?:^\\s*|<\\?(?:php)?\\s*)?\\b(endif|endfor|endforeach|endwhile|endswitch)\\b(?=\\s*;\\s*(?://.*?|/\\*.*?\\*/\\s*?)?(?:\\?>|$))",
            "enabled": true
        }
    ]
```

I personally find PHP angles less useful which is why I have disabled them.  If you find the inverse true, disable the other instead, but to get better conditional support, I would need you to test out the PHP keywords.

Hope that helps.

**Comment by nicolasxu** [comment]
Thanks a lot for helping me understanding the situation!

**Comment by facelessuser** [comment]
Improvements to PHP keywords should be coming in the next release.   I will consider this closed.
