### ISSUE TITLE
Ruby syntax highlight error when a method scope modifier keyword prefixes a method definition

### ISSUE THREAD

**Issue by jjgh** [facelessuser/BracketHighlighter#348]
Not sure if this belongs here, but I found an error with the Ruby syntax highlighting.
Specifically the error happens when a method scope modifier prefixes a method definition like so:

```
private def a_private_method
  # method body
end
```

In this case, when positioning the cursor on the _end_ keyword, BracketHighlighter will fail to identify the method starting keyword _def_

This syntax was introduced in Ruby 2.1 so maybe BracketHighlighter did not catch up with it.
The old syntax did not allow to prefix method with modifiers and you had to write it like this:

```
private :a_private_method

def a_private_method
  # method body
end
```

**Comment by facelessuser** [comment]
Normally rule changes are supported by the community.  As I don't use ruby, this falls into that category, but since I am aware that this ruby rule setup is a little complicated, if this is fairly straight forward, I can patch this.

What are **all** the prefixes that can be used?  I would assume at the very least public and private, but are there more?  Maybe something like protected or anything else?

**Comment by jjgh** [comment]
Public, private and protected should be all of them. 
I checked the official documentation and other sources and couldn't find others so I'd go with those.
Thanks a lot for taking care of this, appreciated.
