### ISSUE TITLE
Bracket highlighter currently listed as missing from packagecontrol.io

### ISSUE THREAD

**Issue by shuhaowu** [facelessuser/BracketHighlighter#351]
If you go to https://packagecontrol.io/packages/BracketHighlighter you'll see that brackethighlighter currently is listed as missing. This means it cannot be installed on a new install:

![screenshot_2016-06-25_23-51-57](https://cloud.githubusercontent.com/assets/338100/16360419/d3a00bf6-3b2f-11e6-9c15-300381563ce2.png)

**Comment by facelessuser** [comment]
This looks like a Package Control issue.  See the recent issue opened: https://github.com/wbond/package_control_channel/issues/5543.

**Comment by facelessuser** [comment]
Basically there is nothing I can do until someone can tell me that I did something wrong recently that broke it, or the issue is resolved on Package Control.  Anyone who is interested in trying the recent version, or just needs to do a fresh install will probably have to just install manually.  Wbond has said he will look into to it probably tomorrow on the Package Control side.

---
### How to install manually
1. Download the latest tag from here: https://github.com/facelessuser/BracketHighlighter/releases.
2. Unpack the zip into your Packages folder (renaming the folder from BracketHighlighter-st3-0.0.0 to just BracketHighlighter).
3. Run Package Control's `Satisfy Dependencies` command to get all the dependencies
4. restart Sublime

Installing with git is also nice an option if you are comfortable with git, but you would still need to do steps 3 and 4.

---

It is our hopes that BracketHighlighter will be returned to us safe and sound.

**Comment by facelessuser** [comment]
It's back.  Had to delete some old tags.  Still think there should be a better way to handle this.

**Comment by AnastasiaDunbar** [comment]
It's missing in my program but doesn't say it on the website.
