### ISSUE TITLE
Why not plain text?

### ISSUE THREAD

**Issue by nicholashh** [facelessuser/BracketHighlighter#367]
### Requirements
**Do not delete this**. Template must be followed or the issue will be marked `Invalid` and closed.

Please mark if you have done done this.  Mark by placing an `x` in the box: `- [ ]` -> `- [x]`.  Support will not be offered without this.

- [x] Search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request. Often the answer to your question is already found there.  You may also find the feature you are requesting already exists. It is okay if after doing this you are still confused, just mention what you didn't understand in the documentation below so we can make it better.

### Description

For bugs, provide errors from console, examples etc.  For feature requests, describe the desired feature.  Be as detailed as possible. Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

> This isn't a bug report; I just have a question about the default settings...
> 
> Essentially, why not plain text?? Personally, if I open up a txt file in Sublime, it's because I want to view it as structurally as possible (fixed-width fonts, etc), so having BH active would be really nice. Obviously you can do this (which I did by downloading the full settings config file and removing all the plain text blacklistings), but I'm just curious: Why isn't the the default?
> 
> Thanks guys! Awesome extension, btw :) -Nick

---

### Issue Support Info

For bugs, run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.  Omit for feature requests.

> n/a

### Steps to Reproduce Issue

Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests.

> n/a

**Comment by facelessuser** [comment]
> Essentially, why not plain text?

This is answered here: https://github.com/facelessuser/BracketHighlighter/issues/137
Specifically here: https://github.com/facelessuser/BracketHighlighter/issues/137#issuecomment-29111069.

I will rephrase and elaborate though.  We capture brackets either by scope and/or regular expression.  Text is not really scoped (or it is all scoped the same), so we can't use scopes.  Text is also not a regular language, therefore regular expressions don't work well.  Text is free form.  Which brackets do I match here?

```
This is an example (mainly to demonstrate why plain text is avoided :) ).
```

I know that the last round bracket should be matched, but how do I tell BH that the smiley round bracket should be ignored?  I have to provide that logic. It isn't contained in a comment scope or a string scope, but it isn't really used as a bracket either.

I hope this illustrates why by default I do not allow bracket finding in plain text.  Feel free to enable it if you like, but understand it's limitations.

**Comment by nicholashh** [comment]
Ahhh, smilies. Good point. I see why that would be hard to check for. I guess all of the text files I look at are more formal than this example and thus don't have that (or a related) problem.

Kind of as a follow up question, tho... Since you mentioned possibly escaping the smiley with quotes, I tried that to see what would happen, only to realize that quote matching isn't working at all (neither single nor double) in my file, even tho plain text has been removed from their blacklists. Do you know why this might be?

**Comment by facelessuser** [comment]
Most of this is covered in the documentation.  But scopes within syntax highlighting are used to find quotes.  Since quotes have an opening marker that looks identical to the closing marker, it becomes very difficult to detect where a string starts and ends without scanning the entire file, but BH doesn't always scan an entire file, but instead uses a sliding window for performance reasons.  We might get confused with apostrophes and quotes etc.  Yes there are heuristics we could add to look for to rule these out to some extent, but I doubt it would be 100% accurate.

What BH does in regards to most brackets where the opening looks like the closing is search for the `string` scope in the view, and then check that the end caps of that scope region are what we expect (and in the case of strings, they would be single or double quotes). 

Since text files don't scope anything as string, but instead just scope everything as `text.plain`, I can't find the quotes with the current method.  You would have to create a rule that didn't use scopes, but as mentioned earlier, I am doubtful of the reliability of a pure regex quote search.

**Comment by nicholashh** [comment]
Ahhh. Again, a very clear answer. Thanks for explaining! :)

**Comment by facelessuser** [comment]
No problem
