### ISSUE TITLE
Spintax Highlight incorrect Brackets

### ISSUE THREAD

**Issue by MaximPro** [facelessuser/BracketHighlighter#383]
Hello,

Thanks for developing this great addon.

However when I testet it with this spintax structure
{Word1|Word2|Word3}

it didn't work.

**What is spintax?**
look here: http://spintaxtool.com

Also there are much more complex spintaxing with up to 10 levels of Inner spin, where it's hard to see, if there is an error, in form of an unlclosed bracket some where. This is where I hoped to get some help out of this addon.

Like this: 
{Words|Word{s|z} {become|are} {crazy|great|amazing} trought the {right|correct|good} placement {with{each other|all of them together}|Word{1|2|3{subword{z|s}|subwords2}}

It would be great if your addon could show unclosed {} brackets.

Here is an error, can your bracket highlighter find it? 
{Words|Word{s|z} {become|are} {crazy|great|amazing} trought the {right|correct|good} placement {with{each other|all of them together|Word{1|2|3{subword{z|s}|subwords2}}

Could you add this features please?
Would be great.

**Comment by facelessuser** [comment]
I'm afraid I need you to follow the template for support: https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md.  Read the template and read this http://facelessuser.github.io/BracketHighlighter/contributing/.  Please provide as much info as you can, such as a link to the syntax highlighter you use etc.

I require everyone to follow the template to get an official response or support.

**Comment by MaximPro** [comment]
What didn't you understand?
What more details do you need?

I used the following template for that above. 
You can't just let all people down, due to not following exactly your template, you are human and should be able to understand what is meant. This isn't a template for a bot/machine.

For feature requests or proposals:
Clearly define in as much detail as possible how you imagine the feature to work.
Examples are also appreciated.
Feature requests and proposals do not require reproduction steps.

**Comment by facelessuser** [comment]
> You are human and should be able to understand what is meant. 

Slow your roll.  This is rude.  You are asking for me to look into something in my free time, but you don't want to do what I ask of you to get a piece of my free time.  I can understand if what I want isn't clear in the template; I can fix that.  But I am not okay with rudeness.

---

So let's step back a minute and take a look.  Maybe there is a misunderstanding here.

You said :

> However when I testet it with this spintax structure
> {Word1|Word2|Word3}
>
> it didn't work.

Sounds like a bug, not a proposal. But even then maybe there just isn't support for spintax language and that is what is being asked. The template also asks people to read this: http://facelessuser.github.io/BracketHighlighter/contributing/.

But I will quote it here:

> The most common requested enhancement for BracketHighlighter is for new rules to add support for {insert your favorite language here}. I, like you, am proficient in very specific languages. I probably don’t use your favorite language or there would already be a support for it. I don’t have time to learn the nuances of your language. For these reasons, support for new language brackets requires pull requests from the community.

> Though I will not personally implement rules for your favorite language, I am more than willing to offer suggestions and guidance to help those who may struggle to create rules for their specific language of interest.

You go on to suggest:

> It would be great if your addon could show unclosed {} brackets.

Sounds like a feature request.

---

So, I am a reasonable guy.  Maybe it isn't clear that I want the structure followed in the templates with headers etc.  I want that.  I will update the template to clearly state that.  Hopefully that is clear now.

I want to know if there is a bug with highlighting or if this is just a feature request.  This was not made clear.  I want as much info as possible.  Is there a highlighter for spintax that you are using?  Or is this just done in plain text syntax highlighting?  I don't know the context of your question.  So please give me all of that in the template structure I provide with version info posted.  Sometimes people are on outdated versions and that is why they see issues.  I think I will probably just require versions even for feature requests to avoid people requesting existing features because they are on an old version.  So I will update the template there as well.

---

The appropriate response in the future is maybe: "what did I do wrong?"  not to insult me with "You are human and should be able to understand what is meant. ".  Am I clear?  Remember, I don't owe anyone anything.  You are **asking** for support.  You don't get to **demand** support.

**Comment by facelessuser** [comment]
I imagine your language isn't working because you are most likely looking at the file in plain text.  All bracket highlighting is excluded from plain text as plain text is free form without predictable structure or scoping context.  

I don't see any spintax highlighters on Package Control, so you should write your own syntax highlighter, or you can enable basic brackets in your local settings.  See documentation for more info.

If your language requires additional rules once it has a syntax highlighter, additional language support can be added via a pull request.

In the future, fill out the template and be respectful.

**Comment by MaximPro** [comment]
Ok well, let me state my position. 
I understand that you do that in your free time and owe the users nothing. this is done by you.
And I also can understand that you need to know as much as possible about the bug.
However instead of just using your time to tell people to use the template, you should ask questions or prepare those questions in your template, because only questions give you awnsers.

Also try more to understand, what the user wants. Because It seems a little bit like you've had enough by user requests etc and  every request pisses you off a little bit, because it means work to do, to think again in how to code that etc. Isn't it behind this? Ask yourself.

But thanks anyway for your help, I can now understand, why it isn't working properly, like I expected it to work, because it does not work in plain text. 
So it would be great if you could just give us an option to let us activate your bracket highlighter even in plain text.

To be honest, I don't know how your highligther works so far, because I didn't saw it in action. I except it to highlight brackets, like the name already suggests. You just highlight some text either with color, bold oder underscore.

So let us choose wich brackets and wich color to highlight it, if it isn't already there. 
We only have these 3 types of brackets: ( ) [ ] { }

Would be great to have it like this:
( ) = bold green 
[ ] = bold orange
{ } = violet


Wouldn't that be a fair option for both of us?

Something like that. It just should be easy!

Because other then programmers the user don't think deep into the matter. 
It's more like activating the light be a switch, either it works or not. I'm also not a programmer, I'm more like an editor and understand the princibles behind the logic and a few things, however I don't speak python, javascript or c++ etc. Only html, css.

Best way to have it is like that logic:
User installs bracket highlighter, a new tab appears with documentaries and how to change the options, maybe even a small tutorial screenplay (youtube) and done! Perfect for everyone, much more stress for you as well.

Sounds reasonable to me and it probably will be nice for future coming users as well as the users you have right now. Just to install it, have them see that it works

Thats just my thoughts as well, thanks man!
Have a great time!

**Comment by facelessuser** [comment]
> Because It seems a little bit like you've had enough by user requests etc and every request pisses you off a little bit, because it means work to do, to think again in how to code that etc. Isn't it behind this? 

You would be wise to not make grand assumptions without experience as a programmer that supports multiple repositories.  What pisses me off is not requests, it is rudeness and disrespect.  My request for you to follow the template was business like and without malice.  You can spin this however you want, but you are in the wrong as you have been both rude and disrespectful.  I ask very little for my time.  I don't ask for money.  But what I do ask is that people simply first **try** to do what they can to help themselves (read the documentation), and simply fill out a template.  Instead of apologizing, you have instead doubled down and added more insults.

I've been patient and even answered your question despite your rudeness, and I have pointed you to the documentation.  You have not read the documentation as all of your current questions would have been answered if you had: colors, enabling brackets in plain text, etc.  By reading the documentation and default settings files, you should get a vague idea of how languages are supported even if the concept of Python and other languages is unfamiliar.

If you choose to read the documentation and are still confused, you can open a new issue and follow the template appropriately, citing what in the documentation you don't understand so it can be further clarified in the future.  I don't expect my documentation to be perfect, and I don't expect all people will understand it easily, so I have no problem addressing confusing concepts.  I am very accommodating to those who are respectful and kind, but my patience only extends so far to those who are not.

There is documentation on this site.  BH may in the future present a message that directs people to the documentation on first install. But in general basic BH works out of the box except in languages that have no formal syntax highlighting support.  Plain text is free form and doesn't have a structure like code does.  This presents difficulties with the current way BH operates.  Things like smilies (which are not meant to be treated as brackets) would be treated as brackets breaking the bracket matching, as would apostrophes and the like.  Code usually has the concept of comments and strings which are scoped in syntax highlighters (that colors the code), and those scopes are used to allow BH to avoid troubling free form text issues in things like comments and strings.  You can already enable these things, and you can change their color as desired.

Again, please direct future questions to a new issue following the template.  I will close the issue promptly next time if rude behavior is displayed.  I am locking this issue.
