### ISSUE TITLE
Question: how to highlight quotes in markdown?

### ISSUE THREAD

**Issue by reagle** [facelessuser/BracketHighlighter#386]
## Description

When editing a markdown file, how can I enable quotations to be highlighted and matched? I'd like to use a shortcut to bounce between the opening and closing, have the icon show up in the gutter, easily select its content, etc.

## Support Info

- ST ver.: 3126
- Platform: osx
- Arch: x64
- Plugin ver.: 2.23.0
- Install via PC: True
- mdpopups ver.: 1.11.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by r-stein** [comment]
The highlighting of quotation marks is based on the scope, but the markdown syntax has no string scope for quotation marks. So you would have to edit your syntax definition to add the `string.quoted` scope for quotation marks.

**Comment by facelessuser** [comment]
Thank you @r-stein.  Yes Markdown syntax would need to have a special syntax for quotes.

This is due to the fact that BH only scans a window of the file for matching the brackets for performance, and since start quotes look the same as end quotes.  Not only that, Markdown, being prose, introduces more complicated situations dealing with quotes as you would need more complicated heuristics, and even then you will still have false positives at times.  So scope context is very important for quote type where start and end brackets look the same.

**Comment by reagle** [comment]
Okay, I'll take that as a non-trivial problem not soon to be addressed. At least I know it's not because I was missing a simple configuration option. I'll close and perhaps if others have the same question they will find this. Thanks for the quick response!

**Comment by facelessuser** [comment]
I'll say this.  You could probably add your own personal rule to do this.  You would have to construct a regex with lookaheads and lookbehinds to get some sense of context for each quote.  You could maybe get it fairly reliable.  It is probably no different than some markdown plugins that convert quotes to fancy quotes, but even those mess up at times.  The only reason I wouldn't spend my time to make this a default rule is because I doubt it would ever be 100% reliable, which means I would get issues regularly filed to fix situations.  I do think it is possible to construct something with maybe 80%-90% reliability for personal use.
