### ISSUE TITLE
feature? remove html attributes

### ISSUE THREAD

**Issue by cjaoude** [facelessuser/BracketHighlighter#393]
a feature to remove html attributes

`
<label class="foo">  ---> <label>
`

**Comment by facelessuser** [comment]
Thank you for your contribution to BracketHighlighter.  Unfortunately BracketHighlighter now requires all issues to follow the [issue template](https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md). 
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Make sure to be as descriptive as possible so I can easily access what your issue is, or what kind of work it would take to implement your feature request.

Once the opening post has been updated, I will be happy to discuss the issue 😄 .

**Comment by facelessuser** [comment]
This request is too vague and and didn't follow the template.  I will give it a couple more days to be updated with more details following the template, and if it is not updated proper, I will close it.
