### ISSUE TITLE
Select Brace Content stopped working

### ISSUE THREAD

**Issue by iamntz** [facelessuser/BracketHighlighter#417]
Hey guys. I've noticed a problem on one of the latest dev release (3133 or 3132, can't really pinpoint), one of which is very annoying and it only happens on PHP files.

I'm on Windows 10, using latest version of BH and sublime. I tried with the portable version of ST, completely cleaned up: no other packages installed other than package control and BH.

Sample:
```
print_r($foo);
print_r($foo->bar());
```

Expected functionality: when i'm inside of the `( brackets )` i should be able to select its content.
Actual behavior: works only only on the first instance (i.e. as soon as i have a non round bracket, nothing happens anymore).

https://img.iamntz.com/jing/video_2017-06-06__42_28.mp4

Thanks!

**Comment by facelessuser** [comment]
Please follow the template and provide support info. I don't know what version of BH you are using.

**Comment by facelessuser** [comment]
Not only do you need to post the support info, but also post relevant syntax highlighter you are using.  It it is the default PHP syntax highlighter, most likely it is because the default highlighters have all been going through a massive overhaul causing scope changes etc.  I suspect the angle in `->` is getting targeted for HTML.  I don't use PHP, so this may require a pull request as I leave most bracket support up to the community, but imagine you just need to add a `scope_exclude` in the angle bracket rule with whatever they use to scope `->`.

**Comment by iamntz** [comment]
Is the latest version available via Package Control... No custom rules, no nothing. It's a sublime as pristine as possible :D 

I'll dig into `scope_exclude` thingy and let you know.

Thanks!

**Comment by facelessuser** [comment]
I know, but the template explains that I want people to run the support command via the menu which copies all that information over to the clipboard so you can copy and paste it here.  People sometimes *think* they have the latest, but don't.  It really helps me as I don't have to guess.

I took a brief look, and I think before I headed into work today.  I don't remember the scope off hand....something.accessor.php, but that seemed to fix the issue in default PHP.  I just added that piece of the scope (not the whole thing) to the `exclude_scope`.

Default syntaxes have really gotten a lot better allowing me to drop 3rd party and custom syntaxes, but they introducing small things like this.  Luckily these kinds of things are pretty easy to patch up.
