### ISSUE TITLE
[Ruby] "return case" breaks parser

### ISSUE THREAD

**Issue by adisos** [facelessuser/BracketHighlighter#425]
Example:
```ruby
def mymethod(arg)
  return case arg
  when 1
    1 + 1
  when 2
    2 + 2
  end
end
```
<img src="https://user-images.githubusercontent.com/592907/28450185-8c082d80-6e07-11e7-83cb-be06b4ea5225.png" height="200">

**Comment by facelessuser** [comment]
1.  Since you didn't follow the template, I'm not sure what version you're on.  I guess I'll assume latest....

2. I don't program in Ruby. I leave language support (for languages I don't use) up to the community.  Unfortunately, I don't have time to learn the all the intricate uses of ruby keywords.  I support a lot of repos.

I am going to need you to take a look at the ruby rules in `bh_core.sublime-settings` and issue a pull request.  I can give some pointers if you get stuck.   Alternatively, you can wait until someone else comes along and fixes it for you.

At the very least I would provide information here outlining the details about your corner case.  It may be helpful to mention other keywords that might fall into a similar corner case so that they can be fixed all at once.  I am guessing this situation is arising because case is preceded by `return` but I am not sure as I haven't really looked into it.

**Comment by adisos** [comment]
Okay, thanks for response. I'll try to fix it myself.

**Comment by facelessuser** [comment]
This regex seems to fix it.  Here we allow return for `if`, `begin`, and `case`.  I would assume if you can return a case, you can probably return an `if`, but I'm not sure if you can return a `begin` or not.  I'll let you run with it, but maybe testing is all you need to do.  If this is all you need, feel free to create a pull request with this, but this would need to be applied to both ruby and embedded ruby in the settings.

```js
"open": "((?:(?<=^)|(?<==)|(?<=<<)|(?<=return))\\s*\\b(?:if|begin|case)\\b(?!:)|^\\s*(?:(?:private|public|protected)\\s*)?def\\b[\\p{Ll}\\p{Lu}]*\\b(?!:)|^\\s*\\b(?:for|until|unless|while|class|module)\\b(?!:)|(?<!:)\\bdo\\b(?!:))"
```

**Comment by adisos** [comment]
Awesome. It works! Thanks!

**Comment by facelessuser** [comment]
Is begin block valid after a return? If not, we still need to restructure the regex.  Please don't forget to issue a pull so we can get it in if it works.

**Comment by adisos** [comment]
> I would assume if you can return a case, you can probably return an if    

yes, you can return `if`

> Is begin block valid after a return?

seems so
<img src="https://user-images.githubusercontent.com/592907/28512641-96871e14-7074-11e7-91e5-4c8cd87122c7.png" height="200" />

**Comment by facelessuser** [comment]
As long as we are targeting valid ruby code, then I think a pull request would be acceptable for this.

**Comment by adisos** [comment]
I didn't notice at first. But it "sees" only parent brackets. For example:
```
def method
  3.times do
    puts "example"
  end
end
```
It highlights "def - end", even if I place cursor on "example"

**Comment by facelessuser** [comment]
![screenshot - 7_27_2017 1_30_28 pm](https://user-images.githubusercontent.com/1055125/28688662-d724b3de-72cf-11e7-8946-53b065ad84ef.png)

Works for me.  Keep in mind, my results are with the default ruby syntax on the latest dev branch.

Regardless, you are more of a Ruby expert than I am.  I don't have time to debug Ruby specific brackets, nor do I know all of the Ruby corner cases to check.  If you have specific questions about BH rules, I can answer those, but again, I am counting on a Ruby user to solve this issue.

**Comment by facelessuser** [comment]
Also, you didn't have to close the pull request, you can update it when you figure out what needs to change.

**Comment by adisos** [comment]
I got you, thanks.

**Comment by facelessuser** [comment]
Okay, I've reread this thread. 

> It highlights "def - end", even if I place cursor on "example"

If quotes is enabled, this should show quotes, so I don't know what was happening on your system.  If you only want highlighting to occur when you select the def or end, and not when your cursor is between them, there is an option for that `match_only_adjacent`.  So this seems to have nothing to do with the main issue discussed in this thread.  From my tests, what I suggested works fine.  Nothing was outlined or explained that didn't work as expected, so I am going forward with my suggestion and if it breaks something in ruby, a ruby user can fix it.
