### ISSUE TITLE
Quickstart Guide has missing images?

### ISSUE THREAD

**Issue by braver** [facelessuser/BracketHighlighter#427]
## Quickstart Guide has missing images

![screen shot 2017-08-11 at 10 16 19](https://user-images.githubusercontent.com/2543659/29205620-54d1d8fc-7e7e-11e7-8ff2-2adec464fc92.png)

I'm seeing big stretched placeholder images instead of something real when opening the Quick Start Guide via package settings, immediately after installing the package via package control.

No useful info in the console or elsewhere.

The source file here seems to be missing images too: https://github.com/facelessuser/BracketHighlighter/blob/master/quickstart.md

**Comment by facelessuser** [comment]
You won't see the images by looking at the file on GitHub. Images are loaded differently for phantoms.

What happens is I reorganized the documents folder and moved the images location, but I also forgot to update the quick start links.

**Comment by facelessuser** [comment]
Next time please do follow the template.  It is difficult for me to get people to follow the template on issues that really require that information, so it helps when everyone sets a good pattern for other issue creators.  Thanks!

The issue has been fixed on master.

**Comment by braver** [comment]
While I understand why you have a template, to be honest I simply wouldn't have reported the issue.

**Comment by facelessuser** [comment]
@braver People want a piece of my time and the only thing I ask is for is that people follow the template.  It requires little effort to do so, and I find it disrespectful when people argue about something that requires so little effort that helps maintaining this package so much.

Please respect the time and effort a developer puts into maintaining these public, free repositories.  It is a lot of work and effort, and this isn't the only repo I support.  Developers may require templates from time to time, and at the very least, even if it takes 30 seconds more, it shows you respect the time and effort the developer is *still* putting in to support these public packages.  Some people think there time is to valuable to waste on such a trivial thing.  How valuable is my time?  How valuable is the package I have provided for you to use?

Next time I will close the issue as invalid. I ask very little from people.  I don't beg for donations, or provide nag popups.  I don't close the issues section and only provide pull request (but sometimes I do consider it).  It is not too much to ask to follow a template.

**Comment by braver** [comment]
Sorry, my wording could've been more friendly. I really appreciate the effort you put into all your packages and contributions to the community at large.

However, I didn't want any of your time. This isn't a support request. I catched a bug and hopefully helped improve the package indirectly. I could have not spent the effort to do so. If you're requiring a higher quality of contribution that's ok, I'm just letting you know that it might also prevent such contributions. 

Again, I understand the need to guard against one-line babelfish support requests. However, I think my report here was clear enough that you were able to fix it quickly. I wasn't going to do a full report with version numbers, installed packages and steps to reproduce for something as obvious as this. If the template were a hard requirement, it would have prevented me and will prevent others from trying to help you catch bugs. If that's ok for you, it's ok for me too.

**Comment by braver** [comment]
Sheesh, did I get out of bed on the wrong side today or what? You make excellent points and I do not disagree. Let me stress I mean no disrespect at all. 

I'm just trying to make a practical point here. I ran into a bug while trying to accomplish something else (it was office hours here, I wanted to be at least somewhat productive), and wanted to let you know quickly. If the template was a hard requirement, I would have dropped it and let someone else find the bug. That's all. I totally get that the template is a minor annoyance versus the value it has for you, but the practical reality will also be it reduces reports. And I think my report was good enough without the template, otherwise I wouldn't have made it. I got the hint by the template being there in the first place. 

It's drive-by-issue-reporting and if not done well it's a time sink for the maintainer. I hope I didn't waste your time by being snarky and am super sorry if you feel disrespected. 

I'm sorry if I came across as annoyed in any way, I'm not. If anyone deserves respect in this community it's you man. If I actually needed a response and expected the bug to be hard to reproduce I would have saved till I had time and put in animated gifs and a complete novel with steps to reproduce. I will next time and will try to put 🦄 's in there or something.

**Comment by facelessuser** [comment]
> I'm sorry if I came across as annoyed in any way, I'm not.

It's okay.  I do really appreciate the apology.  This is definitely a sore nerve for me.

Your information for this issue was perfectly fine, and I don't want you to think it wasn't sufficient.  I didn't reject the issue like I normally do 🙂 . In this case, gifs and such aren't really necessary.

Yes I'm looking for higher quality issues than what I often get, but yours was fine.  I'm not looking for perfect issues.  But what I am *also* looking for is a standardized issue so that generally people know what I expect, and they can look at other issues and see examples for what I expect.  In this case, all I was looking for is this.  It really wouldn't have taken but seconds extra.  I provide a command that captures all the version info in the plugin itself, you just have to run it.

## Description

![screen shot 2017-08-11 at 10 16 19](https://user-images.githubusercontent.com/2543659/29205620-54d1d8fc-7e7e-11e7-8ff2-2adec464fc92.png)

I'm seeing big stretched placeholder images instead of something real when opening the Quick Start Guide via package settings, immediately after installing the package via package control.

No useful info in the console or elsewhere.

The source file here seems to be missing images too: https://github.com/facelessuser/BracketHighlighter/blob/master/quickstart.md

## Support Info

- ST ver.: 3142
- Platform: osx
- Arch: x64
- Plugin ver.: 2.24.2
- Install via PC: True
- mdpopups ver.: 2.1.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

I can't make GitHub enforce template format.  I've essentially done everything I can to encourage people to do so.  I've tried to make it as easy as possible and explain exactly what I want and provide the tools necessary to provide me what I ask for.

I know my latter words come off a bit hard, but I do mean what I said.

With all of that said, I do appreciate the bug report. And I appreciate that it was clear and that I didn't have to do any psychic debugging or pester you for more info.

I personally always *try* to fill out a developers template issue the best I can.  If things aren't applicable, I may put `NA`.  Some templates are sillier than others, but I always try to fill them out to show respect for the work they put into their project.

Again, thanks for being understanding.
