### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by guylepage3** [facelessuser/BracketHighlighter#435]
So we use React.js and I am trying to highlight my HTML tags with an outline but it when i set the tag user preferences it does not seem to work.

Any assistance would be appreciated. Thank you.

Here are my settings;
```
{
    // "default" style defines attributes that
    // will be used for any style that does not
    // explicitly define that attribute.  So if
    // a style does not define a color, it will
    // use the color from the "default" style.
    "default": {
        "icon": "dot",
        "color": "brackethighlighter.default",
        "style": "outline"
    },

    // This particular style is used to highlight
    // unmatched bracket pairs.  It is a special
    // style.
    "unmatched": {
        "icon": "question",
        // "color": "brackethighlighter.unmatched",
        "style": "outline"
    },
    // User defined region styles
    "curly": {
        "icon": "curly_bracket"
        // "color": "brackethighlighter.curly",
        // "style": "underline"
    },
    "tag": {
        "icon": "tag",
        // "endpoints": true,
        // "color": "brackethighlighter.tag",
        "style": "outline"
    }
}
```

**Comment by facelessuser** [comment]
Please follow the issue template (https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md) and post relevant info like what color scheme you are using, and if it is modified, please make available the modified copy, etc.

**Comment by facelessuser** [comment]
Also please post full BH use settings. Now that I've reread, probably don't care about color scheme.

**Comment by guylepage3** [comment]
Ok cool. responding now..

**Comment by guylepage3** [comment]
So i am trying to have my HTML tags and tag endings highlighted. 

But as you can see by the following screen shot i am not seeing any highlighting going on
<img width="494" alt="screenshot 2017-10-01 15 46 48" src="https://user-images.githubusercontent.com/1711854/31058380-9ef7631a-a6c0-11e7-8ac1-ae97ec7d16fd.png">

I have applied the following settings to my Sublime Text User Settings as seen here: http://facelessuser.github.io/BracketHighlighter/usage/

```    
    "match_brackets": false,
    "match_brackets_angle": false,
    "match_brackets_braces": false,
    "match_brackets_content": false,
    "match_brackets_square": false,
    "match_tags": false
```

An FYI: Before I installed the above Sublime Text User Settings I did see a dotted underline beneath the HTML tags.

Then I have tried to apply these "Custom" BracketHighlighter settings as seen below:
```
{
    // "default" style defines attributes that
    // will be used for any style that does not
    // explicitly define that attribute.  So if
    // a style does not define a color, it will
    // use the color from the "default" style.
    "default": {
        "icon": "dot",
        "color": "brackethighlighter.default",
        "style": "outline"
    },

    // This particular style is used to highlight
    // unmatched bracket pairs.  It is a special
    // style.
    "unmatched": {
        "icon": "question",
        // "color": "brackethighlighter.unmatched",
        "style": "outline"
    },
    // User defined region styles
    "curly": {
        "icon": "curly_bracket"
        // "color": "brackethighlighter.curly",
        // "style": "underline"
    },
    "tag": {
        "icon": "tag",
        // "endpoints": true,
        // "color": "brackethighlighter.tag",
        "style": "outline"
    }
}
```

**Comment by facelessuser** [comment]
The template requests the following:

> Run the following command from the menu: Preferences->Package Settings->BracketHighlighter-> Support Info. Post the result here.

Please post that so I can see versions and such.

**Comment by guylepage3** [comment]
- ST ver.: 3143
- Platform: osx
- Arch: x64
- Plugin ver.: 2.25.0
- Install via PC: True
- mdpopups ver.: 2.1.1
- backrefs ver.: 2.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
Here's the thing with JSX.  I don't use JSX.  So I leave new language support up to the community.  I mention this in the documentation as I don't have time to learn the nuances of every language everyone uses. It's not simply highlight HTML in Javascript as JSX is actually a template language which breaks the HTML syntax.

With that said, this is a commonly requested feature and unfortunately, no one has stepped up to the plate.

If you are very interested in JSX support, **maybe** I can look into it **if** I have someone who is familiar with JSX and who is willing to explain the nuances (I really don't have the time to dig around to and test to understand all of this).  This is all assuming that JSX doesn't break the HTML is ways that are so bad it is impossible to reliably identify tags with the current BH system.  Since tags are found with regex, depending on how flexible JSX is, this might be too difficult.

So, from what I understand (with my extremely limited knowledge of JSX), it seems that JSX requires a full tag to be defined as it is a preprocessor on JavaScript that can replace the HTML syntax with code that actually creates the HTML object.  So that is good.  I imagine we don't have to worry about the opening tag getting assigned in one variable and the closing tag in another.  All bets are off if that was the case.

Some starter questions:

1. Where are the template variables allowed: `{some_var}`.  Can they be anywhere?  Or does JSX require sane locations for them?  It is going to be impossible to support JSX if it allows crazy stuff like this `<{tag_name} {attribute_name}={attribute_value}>Content.</{tag_name}>`.

2. Are curly brackets the extent of how JSX tags are modified?  How do you escape curly brackets and show literal ones?

**Comment by guylepage3** [comment]
Ahh... i see.. no worries my friend. i barely sleep as it is so i cannot assist with this. if you have someone assist and update, please let me know..

I have to say.. I am a fan of BracketHighlighter already.. helps me out in so many areas.

Thank you for your hard work. It's GREATLY appreciated. Kudos.

**Comment by facelessuser** [comment]
Okay, them I'll close the issue.

**Comment by facelessuser** [comment]
Actually, since I do get asked this from time to time, I'll leave this open in the hopes that someone will have the time to help out here.  And hopefully this one will keep duplicates from getting opened.

**Comment by facelessuser** [comment]
> I have to say.. I am a fan of BracketHighlighter already.. helps me out in so many areas.

Thank you for your hard work. It's GREATLY appreciated. Kudos.

Oh, and thanks for the kind words! 🙂

**Comment by htchaan** [comment]
![image](https://user-images.githubusercontent.com/2399065/33111765-9d826866-cf8a-11e7-80b7-d5f72fa79426.png)


I can get the JSX HTML highlight working with these settings:

`bh_tag.sublime-settings`:
```json
{
  "tag_mode": [
    {
      "mode": "html",
      "syntax": [
        "JavaScript (Babel)"
      ]
    }
  ]
}
```

`bh_core.sublime-settings`:
```json
{
  "align_content_highlight_bar": true,
  "content_highlight_bar": true,
  "user_brackets": [
    {
      "name": "jsx_angle",
      "open": "(<)(?=[^?%]|$)",
      "close": "(?:(?<=[^?%])|(?<=^))(>)",
      "style": "angle",
      "scope_exclude": [
        "string",
        "comment",
        "keyword.operator",
        "source.ruby.rails.embedded.html",
        "source.ruby.embedded.html",
        "storage.type.function.arrow.js",
        "punctuation.accessor.php",
        "punctuation.accessor.arrow.php"
      ],
      "language_filter": "whitelist",
      "language_list": [
        "JavaScript (Babel)"
      ],
      "plugin_library": "bh_modules.tags",
      "enabled": true
    }
  ]
}
```

**Comment by facelessuser** [comment]
@htchaan, unfortunately, what you have provided is extremely fragile as it assumes the JSX code to be pure HTML.

As the opening poster illustrates, JSX users use substitution to set HTML attributes and such in JSX, and the default HTML profiles in `bh_modules.tags` will not recognize those if they get too advanced.  You'd have to modify the patterns for JSX to allow almost anything in `{}` if used as a HTML attribute.  And even then I'm not sure how complicated of code it allows in those. I'd hope regex would be enough to parse it, but maybe not.  Then if JSX allows substitution of a tag name, we have no way of handling that, unless JSX restricts that in a way that is easily detectable.  But even then, BH may fail as the tag name will be some generic variable name, and we won't know if it is allowed to be  self closing, void, etc.

JSX content is *not* HTML *until* the variable substitutions take place, so you'd need patterns that could recognize JSX tags before substitution.  Which might be possible with regular expression, I just don't know since I don't know JSX well enough to understand how complicated these substitutions can get and how badly it can screw up the syntax.
