### ISSUE TITLE
Bracket not matching up properly in ruby when using guard clause

### ISSUE THREAD

**Issue by adisos** [facelessuser/BracketHighlighter#459]
BH is not matching bracket if used guard clause.
1.
<img src="https://user-images.githubusercontent.com/592907/33016023-1c4304dc-ce17-11e7-85d5-e60ce19e9e2f.png" width="300">

2.
<img src="https://user-images.githubusercontent.com/592907/33016157-9265e3e6-ce17-11e7-889b-27cce00a9225.png" width="300">

I am using Sublime Text 3 build 3143 with the default setting for BH.

Support Info:
- ST ver.: 3143
- Platform: osx
- Arch: x64
- Plugin ver.: 2.26.0
- Install via PC: True
- mdpopups ver.: 3.1.3
- backrefs ver.: 2.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
1. Pictures are good, but please **always** post plain text samples of code as well for easy copy and paste.  This issue's example is very short, but it is really annoying to have to manually translate a person's example from a picture, especially when the example is long.  I will generally ignore issues that provide examples with pictures that have lots of text and no copy/paste sample as well.  Just an FYI.

2.  As for your issue, it is already fixed in the latest BH 2.27.0. So update as it is working there: 

    ![screenshot 2017-11-20 07 04 26](https://user-images.githubusercontent.com/1055125/33022105-3f71086a-cdc1-11e7-89e3-90ccc05c03f8.png)

3. I mentioned this before in #425 , but these kinds of issues are not helpful unless I already use the language, and I don't use Ruby .  If you are not going to provide a pull request, please spend the time to explain in depth how a fix **could** be achieved, or issue a pull request.  Like you could explain that while cases generally (as you requested in #425) can follow `return` statements, it is bad form to have `if` statements follow return statements with `end` blocks etc. and that BH should avoid looking for `end` statements if an `if` block follows a `return`.

    I did try to work on this issue with you on #425, but then you disappeared, so I just implemented a solution.  It wasn't until #452 that I had someone explain in depth how we should approach these kinds of issues.

    Do not assume I know what you are talking about.  Generally it is best to assume that I don't use your language and do not have the time or desire to learn your language's nuances. If I don't use the language, my response is **always** going to be, "please issue a pull request", *unless* the issue creator spends the time to explain the nuances of the issue in detail and offer, at the very least, a high level explanation of a solution, even if they don't understand how to actually implement their suggested solution with code or regular expression.

Anyways, your problem does not exist in the latest release, but please do keep these things in mind if you find another Ruby corner case.  I appreciate the bugs being filed, but it does me no good unless you, the expert Ruby, describes how things *should* be handled.

**Comment by adisos** [comment]
Sorry, @facelessuser
My bad.

As I understood, there is no automated tests, so it's hard to me to make changes.

P.S. you did great job. This plugin is the only reason I'm staying on ST.

**Comment by facelessuser** [comment]
> As I understood, there is no automated tests, so it's hard to me to make changes.

Yeah, it is kind of hard to automate as it would have to be done through the editor to tap into the syntax highlighter and such as brackets are often found by regular expression **and** scopes.  I just don't have the time to implement such a system.  For languages I use, I create user overrides and use the new pattern for like a week to make sure I don't see any issues while using it in actual working environments.  Then if it seems fine, I commit it.

With that said, maybe I can at least implement some tests for the regular expression patterns themselves, even if I can't really  tap into actual scopes.

> P.S. you did great job. This plugin is the only reason I'm staying on ST.

Thanks! I'm always happy to hear some of my plugins are useful to people.
