### ISSUE TITLE
Brackethighlighter Only Works When Changing Settings, Not Working for New Files

### ISSUE THREAD

**Issue by Legio-VI** [facelessuser/BracketHighlighter#462]
## Description

I'm learning how to use GIT right now, so I'm brand new to GIT and Sublime. I installed BracketHighlighter through Package Control. When I go to change text in my user or default settings, the highlighter works perfectly. However, when I create a new file, the highlighter doesn't appear. I've attached a screen grab at the bottom of this request.

## Support Info

- ST ver.: 3143
- Platform: windows
- Arch: x64
- Plugin ver.: 2.27.0
- Install via PC: True
- mdpopups ver.: 3.3.0
- backrefs ver.: 2.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Added Brackethighlighter from Package Control
2. When editing text in the settings, the highlighter works; the highlighter won't work when writing on new file.

[brackethigh.pdf](https://github.com/facelessuser/BracketHighlighter/files/1576760/brackethigh.pdf)

**Comment by facelessuser** [comment]
Because the template wasn't followed, I'm not going to bother to spend much time on this as I would need more info.  So I'm going to take a wild guess and say that BracketHighlighter will not highlight brackets in plain text files.  Plain text has no real structure and scoping, and BracketHighlighter triggers off file scoping to know when it is inside a string or comment etc.

I am assuming that BH stops highlighting in new files because they are plain text.  If you want to highlight in plain text, I suggest reading the documentation to learn how you can customize the existing rules to highlight brackets in plain text.

**Comment by facelessuser** [comment]
Marked as `stale` as I haven't received any additional information to answer this question.  If no further information is given, this issue will be closed in about a week.
