### ISSUE TITLE
Incorrect syntax highlighting for quotes?

### ISSUE THREAD

**Issue by kanlukasz** [facelessuser/BracketHighlighter#507]
## Description

I have a question about highlight matching quote.

Look this two cases:

**1.** Here the quote match is highlighted - it's ok
![bez tytulu2](https://user-images.githubusercontent.com/30685349/49135945-768bad80-f2e8-11e8-942d-3ddfb73279b7.png)

**2**. Here the quote match is **not** highlighted (curly bracket instead is highlighted) - why quotes are not match like in example above?
![bez tytulu](https://user-images.githubusercontent.com/30685349/49135904-5a880c00-f2e8-11e8-967e-8110c514797c.png)

## Support Info

![obraz](https://user-images.githubusercontent.com/30685349/49136047-c79ba180-f2e8-11e8-80cb-b75f547356d7.png)

**Comment by facelessuser** [comment]
This is because PHP syntax is quite invasive and breaks HTML syntax.  Bracket Highlighter has a difficult time resolving such cases.  Syntax and scopes and bracket nesting get all messed up in this case.  Maybe some scope settings can be tweaked for HTML/PHP strings, I'd have to see.  Pull requests are welcome, but if you 'd like me to take a look, please paste a copy and pastable example, and if I get some time, I'll take a look and see if there is a reasonable solution.

**Comment by kanlukasz** [comment]
Ok, i understand. Thanks for your answer.
Below are two examples of this problem:

### Example one:
```
<?php while ($row = mysqli_fetch_array($results)) { ?>
	<tr>
		<td><?php echo $row['name']; ?></td>
		<td><?php echo $row['address']; ?></td>
		<td>
			<a href="index.php?edit=<?php echo $row['id']; ?>" class="edit_btn">Edit</a>
		</td>
		<td>
			<a href="server.php?del=<?php echo $row['id']; ?>" class="del_btn">Delete</a>
		</td>
	</tr>
<?php } ?>
```

### Example two:
```
<?php while ($row = mysqli_fetch_array($results)) { ?>
	<div>
		<img src="/assets/uploads/<?php echo $row['foto']; ?>.png">
	</div>
<?php } ?>
```


If you solve this problem in the future, I will be grateful if you write back here. Thanks a lot and thank you for your time.

**Comment by kanlukasz** [comment]
### Example three:
`In this example its about html syntax only. Inline css style does not highlight matching double quote`
```
<button class="btn" type="submit" name="update" style="background:#556B2F;">update</button>
```
