### ISSUE TITLE
[Question]  Does "bracket_outside_adjacent" applies to tags as well?

### ISSUE THREAD

**Issue by duranivan** [facelessuser/BracketHighlighter#509]
## Description

After reading the documentation and some related issues, I'm still wondering if the setting `    "bracket_outside_adjacent": true` in `bh_core.sublime-settings` applies to html tags as well.

## What is the issue / request ?

Inside brackets (curly, round, square), it's clear that this setting works, that is, when the cursor is somewhere in between the brackets but not adjacent to either the opening or closing bracket, I still get bracket highlighting (see line 8 in the picture), which I find it extremely useful as I can select the content in between brackets with the provided command without having to move the cursor to one of the brackets.

Now, I wonder if I can get the same behavior when I am in between tags (see line 10 in the picture), and not just when the cursor is adjacent to the tag (see line 9 in the picture).

![screen shot 2018-12-09 at 12 16 05 pm](https://user-images.githubusercontent.com/20104703/49694475-8e96e300-fbac-11e8-934f-a2ad7bec3de0.png)

If this is not possible yet, could this feature be implemented?

Thanks in advance!

## Support Info

- ST ver.: 3176
- Platform: osx
- Arch: x64
- Plugin ver.: 2.27.5
- Install via PC: True
- mdpopups ver.: 3.3.4
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
Tags work different from normal brackets. But, as far as outside adjacent is concerned, instead of being between brackets `(| )`, you can be touching the outside `|( )`.  But with tags, this is a little different.  Tags is really just matching `< >`, but applying a BracketHighlighter plugin that then matches tags.  So tags require to to be in or touching an opening or closing tag.  It will not work in this case `<html>    |    </html>`. But it's just based on how tags is implemented. If it worked like normal brackets, you'd still run into issues with HTML content have brackets, so you'd have to disable HTML content bracket matching so it would match the tags.

Hopefully that made sense.

**Comment by duranivan** [comment]
Sure, I understand. Thanks again! I'm closing this then.
