### ISSUE TITLE
HTML highlighting in Smarty .tpl templates

### ISSUE THREAD

**Issue by rusproject** [facelessuser/BracketHighlighter#552]
Can't figure out how to enable HTML tags highlighting in .tpl files.

What have I tried:

1. Open Preferences->Package Settings->BracketHighlighter->Tag Settings
2. Copy "tag_mode": [...] section of bh_tag.sublime-settings to the User modification view
3. Add string "Smarty" inside the default "Syntax": [...] list (right after "Java Server Pages (JSP)" that was there by default).
4. Restart ST3.

It doesn't work, html tags in tpl files are not highlighted in any way.

Please can you help me understand what am I doing wrong. Thank you!

- ST ver.: 3211
- Platform: windows
- Arch: x64
- Plugin ver.: 2.27.9
- Install via PC: True
- mdpopups ver.: 3.7.1
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

**Comment by facelessuser** [comment]
My response is probably similar to what I say in regards to most template languages. Keep in mind I know nothing about smarty tpl.

You might be able to add it like PHP is added. Look in `bh_core.sublime-settings` and `bh_tag`.sublime-settings`. You may run into issues like PHP does though as PHP allows you to insert preprocessing statements that are removed when PHP processes the file. BH expects valid HTML, so when PHP inline blocks and such are included in the tag, it can make it difficult to detect tags.

There are multiple issues that have been filed in the past for things like JSX, Naomi and other templates languages, and other languages that include HTML in them.

https://github.com/facelessuser/BracketHighlighter/issues/532
https://github.com/facelessuser/BracketHighlighter/issues/435

With some languages, like JSX, you could have tag fragments that are included in various functions, and there order would make it difficult to match tags across the page and such. There is a big of complication.

Anyways, I would take a look at past issues and see if any suggestions can help you. If not, you could look into adding support into BH via a pull request, but since I have no immediate need for such functionality, I will probably not be spending time on it myself.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by rusproject** [comment]
Thanks for your response. Let me clear one thing. **Smarty** files (`.tpl` filename extension) look like this:
`<div>normal html content`
**`{openTag}`**`<span>some other html content</span>`**`{/closeTag}`**
`</div>`

I am NOT waiting for BH to highlight these Smarty tags or treat them in any way, it would be nice but not necessary. **I just wanted to highlight those usual HTML tags when selected syntax is not HTML**: I use "Smarty" package for ST3, which extends default HTML syntax highlighting in a way {/smarty} tags are highlighted too. HTML tags in this syntax are highlighted exactly as normal HTML by default.

**Any thoughts how can I achieve this?**

**Comment by facelessuser** [comment]
As I mentioned, you probably want to add the syntax to the appropriate rules and places in the `bh_core.sublime-settings` and `bh_tag.sublime-settings` files. You can search for things like PHP. If you see both PHP and HTML in the rule or option, you probably want to add your smarty tpl syntax to those.

**Comment by facelessuser** [comment]
As for highlighting `{smarty}` tags, you'd probably need a specialized rule to do those, maybe even a BH plugin to help match proper openings to closings. All of this is in the documentation.

**Comment by rusproject** [comment]
It worked! I added `"Smarty",` to bh_tag, (both XML and HTML) and to bh_core under "PHP conditional keywords" but nothing happened. Then I added "Smarty" to "PHP Angle" in bh_core, and for some reason it helped! Still not clear for me how exactly it works, but now I have just what I needed - HTML tags are BH-highlighted in Smarty Syntax files!
Thank you!

**Comment by facelessuser** [comment]
You probably don't need it under PHP angle unless you want to enable PHP `<?PHP ?>` matching, but I'm glad it's working for you.

**Comment by BarbzYHOOL** [comment]
@rusproject can you plz tell me what to do for the best result with Smarty? just trying bracket highlighter for the first time
thanks

**Comment by rusproject** [comment]
> @rusproject can you plz tell me what to do for the best result with Smarty? just trying bracket highlighter for the first time thanks

@BarbzYHOOL
I only managed to make Bracket Highlighter to highlight HTML tags in .tpl files (or any other files with `Smarty` syntax). To do so I added `"Smarty"` to all places (in Bracket-Highlighter settings), where HTML or PHP is present (bh_tag and bh_core settings: open it from `Package Settings` -> `Bracket Highlighter` -> `Bracket Settings` and `Tag Settings`).

I attached these user-settings files, and you can use it as is, or dig through and try to figure out if I there are some superfluous parts, maybe not all stuff that I added is necessary. Or maybe you'll figure out how to make BH to highlight `{Smarty}` pairing tags, that would be very nice.
Let me know if you have any updates about using BH with Smarty, pls

[bh_core.sublime-settings.txt](https://github.com/facelessuser/BracketHighlighter/files/10002828/bh_core.sublime-settings.txt)
[bh_tag.sublime-settings.txt](https://github.com/facelessuser/BracketHighlighter/files/10002829/bh_tag.sublime-settings.txt)
