### ISSUE TITLE
[Question] Brackets highlighting like Bracket Pair Colorizer

### ISSUE THREAD

**Issue by maclam** [facelessuser/BracketHighlighter#555]
Hi,

Is it possible to imitate [**Bracket Pair Colorizer**](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) vscode extension by drawing boxes around brackets and connecting them with a line ? Maybe by coloring the vertical line indent and by underlining via scope selector ?

![c1](https://user-images.githubusercontent.com/22882318/86908963-abdcbc00-c117-11ea-85de-b6e2faced00d.PNG) ![c2](https://user-images.githubusercontent.com/22882318/86908967-aed7ac80-c117-11ea-8c6c-43b9263d919c.PNG)
![c3](https://user-images.githubusercontent.com/22882318/86908971-b008d980-c117-11ea-893d-7cbf555ba7ac.png)

Thank you

**Comment by facelessuser** [comment]
1. All options are covered in the docs. Please search it for all available features: https://facelessuser.github.io/BracketHighlighter/

1. You can modify highlight style with this option: https://facelessuser.github.io/BracketHighlighter/customize/#high_visibility_style

2. Because the API for rendering is more limited than a full HTML browser (like VSCode uses), the best that BracketHighlighter can do in regards to connecting lines is https://facelessuser.github.io/BracketHighlighter/customize/#content_highlight_bar. There are limitations to this approach due to the Sublime API in this case.

I personally never use the highlight bar feature as indent guides are more than enough to highlight:

<img width="474" alt="Screenshot 2020-07-08 07 08 11" src="https://user-images.githubusercontent.com/1055125/86922645-30b0e100-c0ea-11ea-9ce0-2cbfa8b82f34.png">

I'm often using features like https://facelessuser.github.io/BracketHighlighter/customize/#show_offscreen_bracket_popup way more.

Anyways. In short, yes you can kind of do what you wanted, but not exactly, but there are other options that make highlighting quite clear.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by maclam** [comment]
Hi facelessuser,

Thank you for support.
I tried to figure out how to setup to match this in vscode :
![vscode](https://user-images.githubusercontent.com/22882318/87255749-cb644380-c48d-11ea-9e58-d481ea8100fc.gif)

with this settings:
```json
"bracket_outside_adjacent": false,
"content_highlight_bar": true,
"align_content_highlight_bar": true,
"user_bracket_styles": {
    "default": {
        "icon": "dot",
        "color": "bhcustom",
        "style": "outline"
    },
    "square": {
        "icon": "square_bracket",
        "color": "bhcustom",
        "style": "outline"
    },
    "curly": {
        "icon": "curly_bracket",
        "color": "bhcustom",
        "style": "outline"
    },
    "tag": {
        "icon": "tag",
        "color": "bhcustom",
        "style": "outline"
    }
},
"user_scope_brackets": [
    {
        "name": "double_quote",
        "enabled": false
    }
]
```
This is what i get:
![sublime](https://user-images.githubusercontent.com/22882318/87255852-9b697000-c48e-11ea-86eb-ec5f6191e4d9.gif)
Indent guide looks like a glitch and it's so sad about the limitation of Sublime API :( 

And with a default indent guide settings:
![sublime2](https://user-images.githubusercontent.com/22882318/87256034-e5068a80-c48f-11ea-9600-e10146d302ec.gif)
It is also limited, i can't to setup like "bracket_outside_adjacent" setting.
Too bad, I'm going to use a "match_brackets" default settings.

Thank you.

**Comment by facelessuser** [comment]
> Indent guide looks like a glitch and it's so sad about the limitation of Sublime API :(

Yup. Some people like it. I added it mainly as a request, but have never used it seriously.

As I said, I just use the indent guide 🤷.

> It is also limited, i can't to setup like "bracket_outside_adjacent" setting.

Not sure what you meant here.
