### ISSUE TITLE
Not finding an specific function end in Lua

### ISSUE THREAD

**Issue by rogeriodec** [facelessuser/BracketHighlighter#572]
## Description

Using Lua (Roblox Lua), this kind of opening/closing function is not being recognized:

```Lua
Item.MouseLeave:connect(function() 
	-- anything...
end)
```
![image](https://user-images.githubusercontent.com/11199752/97733469-a2a4a000-1ab6-11eb-8798-61c68d5b6628.png)

**Comment by facelessuser** [comment]
Keep in mind that I do not use Lua. I'm usually pretty good about updating languages that I do use that experience issues.

This is because I do not know the nuances of `<insert your favorite language>`, only what I am personally familiar with.

I mainly rely on users of languages I am not familiar with to update support if there are issues via pull requests.

Keep in mind, that some languages can be more difficult to highlight things like this than others (without targeting false positives). This may not be one of those cases, but something to be aware of. Often we use a combination of regex and scopes to find and filter out good and bad cases. Sometimes there are tricky inline cases that cause even more difficult matching.

**Comment by facelessuser** [comment]
If you are looking for me to fix it directly, as I stated, I don't really understand the nuances of Lua.

The current regex looks for these keywords to be first on a line, or at least following a semicolon. This assumption appears to be too restrictive for the case you are having trouble with. By relaxing this constraint, you may have false positive matches for ternary operations, but maybe not. I don't really know the Lua syntax at all. You'd have to determine rules that would be sufficient for Lua, but not so relaxed that you match keywords when you don't want to. Granted, you can restrict scopes to help with that.

Anyways, this is why I don't specifically fix all languages, because it would take me a lot of time to research the syntax of all these unfamiliar languages. But as a user of Lua, you understand better than me what would be best.

I'm open to working with you to come up with a solution, but you'd have to help me understand when a Lua keyword should be matched and not be matched, taking into account situations like ternary operations or inline statements that don't follow normal block syntax with a begin and end keyword.

**Comment by rogeriodec** [comment]
I found the cause of the problem:
Normally a function in Lua opens with `function` and closes with `end`.
In the OP, however, the function is declared inside parentheses. This is where the plugin is getting confused: it is not finding the function, but just the parentheses.
However, if I insert a space between the parentheses and the `function` statement, the plugin will recognize the function again:
![image](https://user-images.githubusercontent.com/11199752/97784055-8f5b0880-1b7a-11eb-95a7-a5f28255fb19.png)
![image](https://user-images.githubusercontent.com/11199752/97784061-97b34380-1b7a-11eb-973f-9e0d2443d311.png)
I don't know how to fix this within RegEx so I don't have to insert a space manually just for the function to be recognized in this case.
Would you help me?

**Comment by facelessuser** [comment]
The current regex ensures that there are spaces, newlines, or semicolons (I think) in front of the function. I believe this was generally done this way to try and ensure functions were at the start of the line. I'm not sure how useful the "space" case is though. Python doesn't do look behinds too well, they must be fixed, so that may be why spaces was added in the hopes it was good enough to prevent functions from being found in odd inline cases, but it seems this not necessarily something we want to avoid.

I don't know how Lua handles ternary if statements or other special cases. I'm not sure if removing this requirement will cause false positives or not. You'd have to experiment and provide apply your knowledge of the Lua syntax to ensure proper keywords are highlighted, but not in undesirable cases.

If all this is too difficult, at the very least, we need details dealing in this issue describing all the cases where keywords should be highlighted and not highlighted.

**Comment by rogeriodec** [comment]
That's the only case I've noticed. 
It seems to be very simple to solve, however, as I said, I don't know how to fix it by myself.
Just create a Lua file and put this to get the error:
```lua
Item.MouseLeave:connect(function() 
	-- anything...
end)
```
Then insert a space after `connect(` and the function will be recognized.
If you don't want to make a generic fix, could you only show me the steps to fix here?

**Comment by facelessuser** [comment]
I don't mind a general fix being provided, I just want to understand the implications of the "fixing" this. Will I add a "fix" that will cause other issues? I don't know Lua, so I don't know what other syntax issues I may create. Are there ever cases where `if` doesn't have an `end` Do I fix this for just functions or for all keywords? Can the issue above also be applied to `if` statements or looping statements?

This is why I'm asking. Any assumption I may make, may not be correct as I don't know the language.

**Comment by rogeriodec** [comment]
As I said, the problem occurs ONLY if `function` has parentheses just to the left. This encapsulation in parentheses is apparently exclusive to Roblox Lua.
All other ways work, no need to worry. However, as I said, I can change it just here, because if there is any other problem, it will only affect me and not other users.

**Comment by rogeriodec** [comment]
It seems to be not so easy to fix, so, nevermind, I'm manually inserting a space between `connect(` and `function` to have the functionality working again...
Thanks for your attention.

**Comment by facelessuser** [comment]
It is not too hard to get what you need. You just need to adjust the regular expression look behinds for function, maybe for all the keywords. I've never gotten a straight answer as to whether there are special cases I should avoid in Lua or not. Will all keywords always have an end keyword? Our are there cases were they won't have any (like ternary operations)?

**Comment by facelessuser** [comment]
To help you understand, this is the kind of collaboration I'm usually looking for when modifying languages I don't use: https://github.com/facelessuser/BracketHighlighter/issues/466.

While I don't specifically need the person to come up with the regex, I need to understand the language issue well enough.

**Comment by facelessuser** [comment]
I may have an idea, maybe we need to qualify Lua keywords differently, but this will really be dependant on me getting the question answered as to whether Lua keywords always have an end, of if they're are some cases, like ternary operations, where this may not be true.

**Comment by facelessuser** [comment]
@rogeriodec  You can try this:

```js
        // Lua
        {
            "name": "lua",
            "open": "\\b(if|function|do|repeat)\\b",
            "close": "\\b(end|until)\\b",
            "style": "default",
            "scope_exclude": ["-keyword"],
            "plugin_library": "bh_modules.luakeywords",
            "language_filter": "allowlist",
            "language_list": ["Lua"],
            "enabled": true
        },
```

You will have to evaluate and let me know if this works in all cases and that there are no side effects. I don't use Lua, so I cannot give a sufficient evaluation.

Basically, we are simplifying the rule to exclude the keywords if they don't break on word boundaries and are not scoped as `keyword`. Maybe for Lua this is more than sufficient, in some languages this may not be sufficient enough, but if possible, something more simple is desired over more complex.

**Comment by facelessuser** [comment]
Seems to work with known cases people have provided me in the past:

<img width="653" alt="Screen Shot 2020-11-08 at 8 52 29 AM" src="https://user-images.githubusercontent.com/1055125/98469951-c4c9ac80-219f-11eb-9668-db8dc663bdee.png">

**Comment by rogeriodec** [comment]
Sorry for my ignorance, I put these settings in Bracket Settings, but it seems not be working.

![image](https://user-images.githubusercontent.com/11199752/98471117-ef7c2b00-21c8-11eb-9496-164444f18e8b.png)

**Comment by facelessuser** [comment]
This is covered in the docs: https://facelessuser.github.io/BracketHighlighter/customize/#bracket-rule-management.

In short, you need to put it under `user_brackets`, then it will override the default.

**Comment by rogeriodec** [comment]
Thanks, but I think I'm doing something wrong because I'm getting this error while saving:
![image](https://user-images.githubusercontent.com/11199752/98481297-05ddb300-21d8-11eb-95db-8370d429fe76.png)

... and if I put it in this structure, I get no errors, but the problem of the OP persists:
```
{
	"user_brackets": [
		// Lua
		{
			"name": "lua",
			"open": "\\b(if|function|do|repeat)\\b",
			"close": "\\b(end|until)\\b",
			"style": "default",
			"scope_exclude": ["-keyword"],
			"plugin_library": "bh_modules.luakeywords",
			"language_filter": "allowlist",
			"language_list": ["Lua"],
			"enabled": true
		}
	]
}
```

**Comment by facelessuser** [comment]
You'll have to forgive me as I am usually assuming some degree of understanding of Sublime settings, but I do realize that not everyone has been using Sublime long enough. Yes, you have to put it in a dictionary/hash structure where `user_brackets` is the the key and the value is an array of rules. In this way, the Lua rule will override the default:

```js
{
    "user_brackets": [
        // Lua
        {
            "name": "lua",
            "open": "\\b(if|function|do|repeat)\\b",
            "close": "\\b(end|until)\\b",
            "style": "default",
            "scope_exclude": ["-keyword"],
            "plugin_library": "bh_modules.luakeywords",
            "language_filter": "allowlist",
            "language_list": ["Lua"],
            "enabled": true
        }
    ]
}
```

![lua](https://user-images.githubusercontent.com/1055125/98482712-72e54e80-21c0-11eb-92e4-ce7fa1d62b31.gif)

**Comment by rogeriodec** [comment]
Unfortunately, with these new settings, now, even the spaces between `connect(` and `function` are not working.
Removing these new settings, at least the previous behavior is working.
![r](https://user-images.githubusercontent.com/11199752/98483103-8a363300-21e4-11eb-808e-5a4a0a048ae1.gif)

**Comment by facelessuser** [comment]
I'm not sure what you are doing wrong as I demonstrated in the gif that is working fine.

**Comment by facelessuser** [comment]
If you are using a Lua highlighter that is not scoping function as a keyword, then it is possible that is why it is failing. Can you check the scope of the function keyword?

**Comment by facelessuser** [comment]
I believe it is `ctrl` + `shift` + `p` will get the scope when your cursor is on `function`. Also, what version of Sublime are you on? Sublime versions should always be provided on such issues.

**Comment by rogeriodec** [comment]
I'm using ST 3.2.2 Build 3211.
But never mind, I'll just continue with my previous interim solution.
Thank you again.

**Comment by facelessuser** [comment]
Ah, 3211, I'm on ST4, I bet the Lua syntax file has changed. If you can get me the scope I asked for, I can probably fix it for ST3.

**Comment by facelessuser** [comment]
As I mentioned, ST4 syntax for Lua has had some improvements, so to get this working in ST3, we have to add some additional parameters to get functions to highlight proper:

```js
{
    "user_brackets": [
        // Lua
        {
            "name": "lua",
            "open": "\\b(if|function|do|repeat)\\b",
            "close": "\\b(end|until)\\b",
            "style": "default",
            "scope_exclude": ["-keyword"],
            "scope_exclude_exceptions": ["storage.type.function.lua"],
            "plugin_library": "bh_modules.luakeywords",
            "language_filter": "allowlist",
            "language_list": ["Lua"],
            "enabled": true
        }
    ]
}
```

I leave this here for those interested. I will probably just add it to BH and if it breaks something, Lua users can pull request a fix, but I don't think I'm going to spend any more time on this.

**Comment by rogeriodec** [comment]
I confirm that it's finally working. 
Thank you very much for all your attention and effort!

**Comment by facelessuser** [comment]
I will leave this open until a submit the fix in the default configuration.
