### ISSUE TITLE
Appears to no longer work with Sublime text 4 after recent update

### ISSUE THREAD

**Issue by Kurohyou** [facelessuser/BracketHighlighter#590]
## Description

Since the update ([d483a48](https://github.com/facelessuser/BracketHighlighter/commit/d483a4889a0d8b81d0647335ccb707dab064a92e)), bracketHighlighter seems to no longer work with Sublime Text 4. Not sure what other information to provide, there is no error, the brackets just aren't highlighted other than for the default sublime text underlining. The package was working yesterday.

No errors seen. Current Brackethighlighter packege settings:
`
{
	"content_highlight_bar":true,
	"show_in_minimap":true,
	"show_bracket_popup_always": true,
	"search_threshold":10000,
    "content_highlight_bar": true,
    "align_content_highlight_bar": true,
}
`
Current behavior seen:
![brackethighi](https://user-images.githubusercontent.com/18427622/125179252-34b68980-e1aa-11eb-8dc5-e13177490e45.gif)

## Support Info

...

> Run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.
- ST ver.: 4107
- Platform: windows
- Arch: x64
- Plugin ver.: 2.29.2
- Install via PC: True
- mdpopups ver.: 4.1.2
- backrefs ver.: 5.0
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

1. Open sublime text
2. Open a file that should have brackets highlighted (I have seen lack of highlighting in JS, HTML, and CSS/SCSS files)
3. note that highlighting is not occurring

**Comment by facelessuser** [comment]
> Since the update (d483a48), bracketHighlighter seems to no longer work with Sublime Text 4. Not sure what other information to provide, there is no error, the brackets just aren't highlighted other than for the default sublime text underlining. The package was working yesterday.

1. That commit revision change has absolutely no functional change.
2. If there was any change that "might" affect JS, HTML, and or CSS/SCSS files, it would be https://github.com/facelessuser/BracketHighlighter/commit/0936708344d12f41205f1bf378f9424f7e7549c6.

With that said, that change does not break anything and only fixes an issue related to HTML tag detection when JS is embedded in the HTML and it has `=>`. This was due to recent scope changes in the Default Javascript syntax in ST4.

Syntax Highlighting is still working for JS:

<img width="555" alt="Screen Shot 2021-07-10 at 9 18 06 PM" src="https://user-images.githubusercontent.com/1055125/125181756-5a04c100-e1c5-11eb-9f25-490e077c2b91.png">

HTML:

<img width="810" alt="Screen Shot 2021-07-10 at 9 16 54 PM" src="https://user-images.githubusercontent.com/1055125/125181766-6c7efa80-e1c5-11eb-8fa6-b3b25fc359a2.png">

And CSS/SCSS:

<img width="474" alt="Screen Shot 2021-07-10 at 9 26 47 PM" src="https://user-images.githubusercontent.com/1055125/125181788-96382180-e1c5-11eb-93de-992875e4cfc3.png">

While your mileage may vary depending on whether you are using some 3rd party plugin for syntax highlighting of any of these languages, it still works fine.

I am currently on the latest dev release of ST:

<img width="329" alt="Screen Shot 2021-07-10 at 9 18 38 PM" src="https://user-images.githubusercontent.com/1055125/125181812-c67fc000-e1c5-11eb-8621-ab63b99ef8e6.png">

Sometimes, when an update for BH occurs, it is necessary to restart Sublime. I'd also check if the update didn't quite go right and Package Control still accidentally has BH in the ignore list as plugins are placed there during updates.

**Comment by Kurohyou** [comment]
Huh, had tried to restart sublime to see if that fixed it, but did it again and now it's working
