### ISSUE TITLE
Problem with matching curly brace that is part of a Bash string equivalency test

### ISSUE THREAD

**Issue by luckman212** [facelessuser/BracketHighlighter#627]
## Description

BH _seems_ to be incorrectly matching a curly bracket that is part of a Bash string equivalency test. Not sure if there's a workaround.

Here's a small example:

```bash
#!/usr/bin/env bash

res='{ "foo": 123 }'

if [[ ${res:0:1} != '{' ]]; then
  echo 1>&2 "error in response from API"
  exit 1
fi
```

Screenshot:

<img width="820" alt="image" src="https://github.com/facelessuser/BracketHighlighter/assets/1992842/b32f3a0c-6255-4482-bc2d-de7841a6206c">

## Support Info

- ST ver.: 4172
- Platform: osx
- Arch: arm64
- Plugin ver.: 2.31.2
- Install via PC: True
- mdpopups ver.: 4.2.2
- backrefs ver.: 5.5.1
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

**Comment by facelessuser** [comment]
It looks likes your syntax highlighter doesn't scope the bracket in question as a string. That context is necessary for BH to work properly. This seems like a syntax issue, not a BH Issue. It's possible if it is scoped as a common scope that should be ignored generally, we could alter the rule, but I suspect it should be a string and is just a syntax bug.

**Comment by luckman212** [comment]
Thanks @facelessuser 

So the "problem" is with the Bash syntax highlighter native to ST? I don't know if this is changeable? If it is, I don't know how to do it.

If we only change 1 character, curly brace `{` → letter `a` for example, there is no problem

```bash
#!/usr/bin/env bash

res='{ "foo": 123 }'

if [[ ${res:0:1} != 'a' ]]; then
  echo 1>&2 "error in response from API"
  exit 1
fi
```

![image](https://github.com/facelessuser/BracketHighlighter/assets/1992842/2fd0ddd9-ec4d-4db9-81ef-53c4dd6e63b3)

**Comment by facelessuser** [comment]
Turns out they are scoped, but not as a normal string. I couldn't tell because your syntax highlighter made them look all white as if they were not scoped.

<img width="1071" alt="Screenshot 2024-02-25 at 11 06 52 AM" src="https://github.com/facelessuser/BracketHighlighter/assets/1055125/6b0bdfd0-6f3f-4e3c-8781-8dcbc10d4530">

So we have to update the single quote rule and double quote rule to look for the scope `meta.string.regexp.shell` and then tell the curly, round, and square rule to ignore `meta.string.regexp.shell`. Then it works:

<img width="488" alt="Screenshot 2024-02-25 at 11 06 38 AM" src="https://github.com/facelessuser/BracketHighlighter/assets/1055125/79fc5b84-7e06-4ea8-b4c7-cfb3cbeaec5e">

**Comment by luckman212** [comment]
Thanks - I don't have whatever plugin you seem to be using to show the scopes. And not sure how to edit the syntax rules either (never done it before). Do you suggest doing this? Or should I just leave this alone...

**Comment by facelessuser** [comment]
It can be done locally, but I'll be issuing an update to the rules, so you can wait until then.

**Comment by facelessuser** [comment]
@luckman212 fix has been released. Give package control time to see it though. It could take up to two hours.

**Comment by luckman212** [comment]
@facelessuser Amazing, this is super helpful. Confirmed it's working.

Thanks for fixing on a Sunday 🚀 

<img width="450" alt="image" src="https://github.com/facelessuser/BracketHighlighter/assets/1992842/dcd44078-5ba9-46d5-bc40-b9ad378900b7">
